/- Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
This file was machine generated by Codex.
-/

import Mathlib.Analysis.SpecialFunctions.Sqrt
import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Data.EReal.Basic
import Mathlib.Order.LiminfLimsup
import Mathlib.Data.Fintype.Pi

/-!
# Weak Hellinger inequality and the three-point inequality

Source: Polona Durcik, Marco Fraccaroli and Joris Roos,
"A weak Hellinger inequality for noisy Boolean channels",
arXiv:2609.28534v1 [cs.IT], 2026, https://arxiv.org/abs/2609.28534v1.
The selected results are Theorem 1.1 and Proposition 2.1, including equality cases.

The cube is encoded by `Fin n -> Fin 2`. The weak Hellinger statement also covers
$n=0$, whereas the paper assumes $n\geq 1$. Both functions are explicitly assumed
to take values in $\{-1,1\}$. The conditional expectation is a finite probability
ratio, assigned zero on null conditioning events; those events do not affect the
outer expectation. The output cube is uniform under the symmetric noise kernel.

The three-point definitions reproduce the paper's upper-limit extension of $R$.
Binary divergence takes values in the extended reals, with zero at equal endpoints
and infinity at unequal pairs with second argument an endpoint. Values outside
the stated domains are immaterial. No hypotheses beyond the displayed parameter
ranges and Boolean-valuedness are imposed. These results concern one-bit output
statistics; they do not assert the full Hellinger conjecture.
-/

namespace WeakHellinger

noncomputable section

open Real Set Filter
open scoped Classical



/-- The $n$-dimensional Hamming cube, with 0 encoding +1 and 1 encoding -1. -/
abbrev HammingCube (n : ℕ) := Fin n → Fin 2

/-- A real-valued function on the Hamming cube; sign-valuedness is a separate hypothesis. -/
abbrev BooleanFunc (n : ℕ) : Type := HammingCube n → ℝ

/-- `BooleanValued f` means that `f` takes values `±1`. -/
def BooleanValued {n : ℕ} (f : BooleanFunc n) : Prop :=
  ∀ x, f x = 1 ∨ f x = -1

/-- Expectation with respect to uniform distribution. -/
def expectation {n : ℕ} (f : BooleanFunc n) := (∑ x, f x) / (2 : ℝ) ^ n

@[inherit_doc]
scoped notation "𝐄" => expectation

/--
Noise kernel for correlation parameter `ρ ∈ [-1,1]`, i.e.
the conditional probability `P(Y = y | X = x)`. -/
def noiseKernel {n : ℕ} (ρ : ℝ) (x y : HammingCube n) : ℝ :=
  ∏ i, if x i = y i then (1 + ρ) / 2 else (1 - ρ) / 2

/--
Ad-hoc definition of the conditional expectation occurring in this project, i.e.
`E[f(X) | g(Y) = b]` for uniform `X` and `ρ`-correlated `Y` at `b`.

**Implementation note:** If the event in the denominator has zero probability,
the Lean junk value for zero division will be reached, but it provides the
correct intended value of zero here. -/
def conditionalExpectation {n : ℕ} (ρ : ℝ) (f : BooleanFunc n)
    (g : BooleanFunc n) (b : ℝ) : ℝ :=
  𝐄 (fun x ↦ ∑ y, if g y = b then noiseKernel ρ x y * f x else 0) /
    𝐄 (if g · = b then 1 else 0)

@[inherit_doc]
scoped notation "𝐄_" ρ:max "[" f:51 " ∣ " g "]" y =>
  conditionalExpectation ρ f g (g y)

/-- For a real number `r`, its "complement" is `1 - r`. -/
def bar (r : ℝ) : ℝ := 1 - r

/-- Binary Kullback-Leibler divergence as extended real.
Note it is actually nonnegative. -/
def D (p q : ℝ) : EReal :=
  if p ∈ Icc 0 1 ∧ q ∈ Icc 0 1 then
    if p = q then 0
    else if q = 0 ∨ q = 1 then ⊤
    else if p = 0 then -log (bar q)
    else if p = 1 then -log q
    else p * log (p / q) + bar p * log (bar p / bar q)
  else 0

/-- The semicircle function `h(x) = √(1 - x²)`. -/
def h (x : ℝ) : ℝ := √(1 - x ^ 2)

/-- The open unit cube with the diagonal $c=d$ removed. -/
def U := {(s, c, d) : ℝ × ℝ × ℝ | s ∈ Ioo 0 1 ∧ c ∈ Ioo 0 1 ∧ d ∈ Ioo 0 1 ∧ c ≠ d}

/-- The square root of the binary divergence quotient on $U$. -/
def R_interior (s c d : ℝ) : ℝ :=
  √((D (s * bar c + bar s * d) (s * bar d + bar s * c)).toReal /
    (s * (D c d).toReal + bar s * (D d c).toReal))

/-- The divergence quotient on $U$, extended to the closed unit cube by its
upper limit along $U$. Its value outside the closed cube is zero. -/
def R (s c d : ℝ) : ℝ :=
  if (s, c, d) ∈ U then R_interior s c d
  else if s ∈ Icc 0 1 ∧ c ∈ Icc 0 1 ∧ d ∈ Icc 0 1 then
    limsup (fun (s, c, d) ↦ R_interior s c d) (nhdsWithin (s, c, d) U)
  else 0

/-- The three-point inequality's left-hand side on the closed cube. -/
def F (s c d : ℝ) : ℝ :=
  1 - h (s * (bar d - d) + bar s * (c - bar c)) +
    s * h (bar d - d) + bar s * h (c - bar c) - R s c d


end

open Set
open scoped WeakHellinger

/-- For every natural number $n$, every $\rho\in[-1,1]$, and all
Boolean-valued functions $f,g$ on the $n$-dimensional Hamming cube,
$$
\sqrt{1-(\mathbf{E}f)^2}
-\mathbf{E}_y\sqrt{1-(\mathbf{E}_{\rho}[f\mid g](y))^2}
\leq 1-\sqrt{1-\rho^2}.
$$
-/
theorem weak_hellinger {n : ℕ} {ρ : ℝ} (hρ : ρ ∈ Icc (-1) 1) {f g : BooleanFunc n}
    (hf : BooleanValued f) (hg : BooleanValued g) :
    √(1 - (𝐄 f) ^ 2) - 𝐄 (fun y ↦ √(1 - (𝐄_ ρ [f ∣ g] y) ^ 2)) ≤
      1 - √(1 - ρ ^ 2) := by
  sorry

/-- For every $s,c,d\in[0,1]$, the three-point expression satisfies
$$
0\leq F(s,c,d).
$$
-/
theorem three_point_inequality {s c d : ℝ}
    (hs : s ∈ Icc 0 1) (hc : c ∈ Icc 0 1) (hd : d ∈ Icc 0 1) : 0 ≤ F s c d := by
  sorry

/-- For every $s,c,d\in[0,1]$, equality in the three-point inequality
holds exactly in the following cases:
$$
F(s,c,d)=0\quad\Longleftrightarrow\quad
s=0\ \text{or}\ s=1\ \text{or}\ c+d=1\ \text{or}\ (s=1/2\ \text{and}\ c=d).
$$
-/
theorem three_point_inequality_equality {s c d : ℝ}
    (hs : s ∈ Icc 0 1) (hc : c ∈ Icc 0 1) (hd : d ∈ Icc 0 1) :
    F s c d = 0 ↔ s = 0 ∨ s = 1 ∨ c + d = 1 ∨ (s = 2⁻¹ ∧ c = d) := by
  sorry

end WeakHellinger
