/- Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
This file was machine generated by Codex.
-/

import Mathlib.Analysis.SpecialFunctions.Sqrt
import Mathlib.Data.Fintype.Pi

/-!
# Weak Hellinger inequality

Source: Polona Durcik, Marco Fraccaroli and Joris Roos,
"A weak Hellinger inequality for noisy Boolean channels",
arXiv:2609.28534v1 [cs.IT], 2026, https://arxiv.org/abs/2609.28534v1.
The selected result is Theorem 1.1. The supporting three-point inequality and
its equality cases remain in the proof development and are not selected here.

The cube is encoded by `Fin n -> Fin 2`. The weak Hellinger statement also covers
$n=0$, whereas the paper assumes $n\geq 1$. Both functions are explicitly assumed
to take values in $\{-1,1\}$. The conditional expectation is a finite probability
ratio, assigned zero on null conditioning events; those events do not affect the
outer expectation. The output cube is uniform under the symmetric noise kernel.

No hypotheses beyond the displayed parameter range and Boolean-valuedness are
imposed. This result concerns one-bit output statistics; it does not assert the
full Hellinger conjecture.
-/

namespace WeakHellinger

noncomputable section

open Real Set
open scoped Classical

/-- The $n$-dimensional Hamming cube, with 0 encoding +1 and 1 encoding -1. -/
abbrev HammingCube (n : ℕ) := Fin n → Fin 2

/-- A real-valued function on the Hamming cube; sign-valuedness is a separate hypothesis. -/
abbrev BooleanFunc (n : ℕ) : Type := HammingCube n → ℝ

/-- `BooleanValued f` means that `f` takes values `±1`. -/
def BooleanValued {n : ℕ} (f : BooleanFunc n) : Prop :=
  ∀ x, f x = 1 ∨ f x = -1

/-- Expectation with respect to uniform distribution. -/
def expectation {n : ℕ} (f : BooleanFunc n) := (∑ x, f x) / (2 : ℝ) ^ n

@[inherit_doc]
scoped notation "𝐄" => expectation

/--
Noise kernel for correlation parameter `ρ ∈ [-1,1]`, i.e.
the conditional probability `P(Y = y | X = x)`. -/
def noiseKernel {n : ℕ} (ρ : ℝ) (x y : HammingCube n) : ℝ :=
  ∏ i, if x i = y i then (1 + ρ) / 2 else (1 - ρ) / 2

/--
Ad-hoc definition of the conditional expectation occurring in this project, i.e.
`E[f(X) | g(Y) = b]` for uniform `X` and `ρ`-correlated `Y` at `b`.

**Implementation note:** If the event in the denominator has zero probability,
the Lean junk value for zero division will be reached, but it provides the
correct intended value of zero here. -/
def conditionalExpectation {n : ℕ} (ρ : ℝ) (f : BooleanFunc n)
    (g : BooleanFunc n) (b : ℝ) : ℝ :=
  𝐄 (fun x ↦ ∑ y, if g y = b then noiseKernel ρ x y * f x else 0) /
    𝐄 (if g · = b then 1 else 0)

@[inherit_doc]
scoped notation "𝐄_" ρ:max "[" f:51 " ∣ " g "]" y =>
  conditionalExpectation ρ f g (g y)


end

open Set
open scoped WeakHellinger

/-- For every natural number $n$, every $\rho\in[-1,1]$, and all
Boolean-valued functions $f,g$ on the $n$-dimensional Hamming cube,
$$
\sqrt{1-(\mathbf{E}f)^2}
-\mathbf{E}_y\sqrt{1-(\mathbf{E}_{\rho}[f\mid g](y))^2}
\leq 1-\sqrt{1-\rho^2}.
$$
-/
theorem weak_hellinger {n : ℕ} {ρ : ℝ} (hρ : ρ ∈ Icc (-1) 1) {f g : BooleanFunc n}
    (hf : BooleanValued f) (hg : BooleanValued g) :
    √(1 - (𝐄 f) ^ 2) - 𝐄 (fun y ↦ √(1 - (𝐄_ ρ [f ∣ g] y) ^ 2)) ≤
      1 - √(1 - ρ ^ 2) := by
  sorry

end WeakHellinger
