/- Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
This file was machine generated by Codex.
-/

import WeakHellinger.Theorems

/-!
# Palomar solution surface

The canonical declarations are imported directly from `WeakHellinger/Theorems.lean`.
Their proofs are in `WeakHellinger/Auto/Reduction.lean` and
`WeakHellinger/Auto/ThreePointInequality.lean`, with the exact computational
certificate in `WeakHellinger/Auto/FiniteCertificate.lean` and the information-theory
prerequisites in `WeakHellinger/Auto/ReverseHypercontractivity.lean`.
-/
