/- Copyright (c) 2026 Joris Roos.
Released under Apache 2.0 license as described in the file LICENSE.
This file was automatically generated by Codex.
-/
import Mathlib.Analysis.SpecialFunctions.Sqrt
import Mathlib.Analysis.SpecialFunctions.Log.Deriv
import Mathlib.Tactic

/-!
# Reduction of weak Hellinger to the three-point inequality

The only additional axiom is the exact statement of `Auto.three_point_inequality`
from `ThreePointInequality.lean`. Its definition closure below is copied unchanged.
This file deliberately imports only Mathlib and does not load the finite certificate.

Source: the user's proposition `prop:three-point-implies-main` and its proof.
The reverse-hypercontractivity input must be proved, not assumed.
-/

namespace Auto

noncomputable def r (x : ℝ) : ℝ := Real.sqrt (1 - x ^ 2)

noncomputable def D (u v : ℝ) : ℝ :=
  u * Real.log (u / v) + (1 - u) * Real.log ((1 - u) / (1 - v))

noncomputable def K (u v : ℝ) : ℝ :=
  if u ∈ Set.Ioo (0 : ℝ) 1 ∧ v ∈ Set.Ioo (0 : ℝ) 1 then
    if u = v then 1 / (2 * v * (1 - v)) else D u v / (u - v) ^ 2
  else 0

def p (s c d : ℝ) : ℝ := s * (1 - c) + (1 - s) * d

def q (s c d : ℝ) : ℝ := s * (1 - d) + (1 - s) * c

noncomputable def Rdenominator (s c d : ℝ) : ℝ := s * K c d + (1 - s) * K d c

noncomputable def R (s c d : ℝ) : ℝ :=
  if s ∈ Set.Icc (0 : ℝ) 1 ∧ c ∈ Set.Icc (0 : ℝ) 1 ∧ d ∈ Set.Icc (0 : ℝ) 1 then
    if c ∈ Set.Ioo (0 : ℝ) 1 ∧ d ∈ Set.Ioo (0 : ℝ) 1 then
      Real.sqrt (K (p s c d) (q s c d) / Rdenominator s c d)
    else if s = 0 ∨ s = 1 ∨ c + d = 1 then 1 else 0
  else 0

/-- The sole user-authorized assumption, with the original statement unchanged. -/
axiom three_point_inequality {s c d : ℝ} (hs : s ∈ Set.Icc (0 : ℝ) 1)
    (hc : c ∈ Set.Icc (0 : ℝ) 1) (hd : d ∈ Set.Icc (0 : ℝ) 1) :
    r (2 * q s c d - 1) - s * r (2 * d - 1) -
      (1 - s) * r (2 * c - 1) + R s c d ≤ 1

/-- The binary mean appearing in the reduction equals `2q-1`. -/
theorem reduction_mean (s c d : ℝ) :
    s * ((1-d)-d) + (1-s) * (c-(1-c)) = 2 * q s c d - 1 := by
  unfold q
  ring

/-- The final algebraic step, once the channel estimate for `R` is proved. -/
theorem reduction_of_channel_bound {s c d ρ : ℝ}
    (hs : s ∈ Set.Icc (0 : ℝ) 1) (hc : c ∈ Set.Icc (0 : ℝ) 1)
    (hd : d ∈ Set.Icc (0 : ℝ) 1) (hchannel : Real.sqrt (1-ρ^2) ≤ R s c d) :
    r (s * ((1-d)-d) + (1-s) * (c-(1-c))) -
      (s * r ((1-d)-d) + (1-s) * r (c-(1-c))) ≤ 1-Real.sqrt (1-ρ^2) := by
  have h := three_point_inequality hs hc hd
  have hd' : r ((1-d)-d) = r (2*d-1) := by
    unfold r
    congr 1
    ring
  have hc' : c-(1-c) = 2*c-1 := by ring
  rw [reduction_mean, hd', hc']
  linarith

/-- Cross-entropy expansion, valid also at `x=0` and `x=1` with interior reference. -/
theorem reduction_D_expand (x v : ℝ) (hv : v ∈ Set.Ioo (0 : ℝ) 1) :
    D x v = x * Real.log x + (1-x) * Real.log (1-x) -
      x * Real.log v - (1-x) * Real.log (1-v) := by
  have hv0 : v ≠ 0 := ne_of_gt hv.1
  have hv1 : 1-v ≠ 0 := ne_of_gt (sub_pos.mpr hv.2)
  by_cases hx0 : x = 0
  · subst x
    simp [D]
  by_cases hx1 : 1-x = 0
  · have hx : x = 1 := by linarith
    subst x
    simp [D]
  unfold D
  rw [Real.log_div hx0 hv0, Real.log_div hx1 hv1]
  ring

/-- Nonnegativity of binary KL with an interior reference law. -/
theorem reduction_D_nonneg {x v : ℝ} (hx : x ∈ Set.Icc (0 : ℝ) 1)
    (hv : v ∈ Set.Ioo (0 : ℝ) 1) : 0 ≤ D x v := by
  by_cases hx0 : x = 0
  · subst x
    simp only [D, zero_div, zero_mul, sub_zero, one_mul, zero_add]
    exact Real.log_nonneg (by apply (le_div_iff₀ (sub_pos.mpr hv.2)).mpr; linarith [hv.1])
  by_cases hx1 : x = 1
  · subst x
    simp only [D, one_mul, sub_self, zero_div, zero_mul, add_zero]
    exact Real.log_nonneg ((le_div_iff₀ hv.1).mpr (by linarith [hv.2]))
  have hxp : 0 < x := lt_of_le_of_ne hx.1 (Ne.symm hx0)
  have hxm : 0 < 1-x := by have := lt_of_le_of_ne hx.2 hx1; linarith
  have h1 := mul_le_mul_of_nonneg_left
    (Real.log_le_sub_one_of_pos (div_pos hv.1 hxp)) hxp.le
  have h2 := mul_le_mul_of_nonneg_left
    (Real.log_le_sub_one_of_pos (div_pos (sub_pos.mpr hv.2) hxm)) hxm.le
  rw [Real.log_div (ne_of_gt hv.1) (ne_of_gt hxp)] at h1
  rw [Real.log_div (ne_of_gt (sub_pos.mpr hv.2)) (ne_of_gt hxm)] at h2
  have e1 : x * (v/x-1) = v-x := by field_simp
  have e2 : (1-x) * ((1-v)/(1-x)-1) = (1-v)-(1-x) := by field_simp
  rw [e1] at h1
  rw [e2] at h2
  rw [reduction_D_expand x v hv]
  nlinarith

/-- Complementing both Bernoulli laws preserves their divergence. -/
theorem reduction_D_complement (x v : ℝ) : D (1-x) (1-v) = D x v := by
  unfold D
  simp only [sub_sub_cancel]
  ring

/-- Exact Pythagorean identity for the swapped conditional laws.
The constraint eliminates the common log-odds multiplier. -/
theorem reduction_swap_identity {s c d x y : ℝ}
    (hc : c ∈ Set.Ioo (0 : ℝ) 1) (hd : d ∈ Set.Ioo (0 : ℝ) 1)
    (hconstraint : s*x + (1-s)*y = s*(1-c)+(1-s)*d) :
    s*D x (1-d)+(1-s)*D y c - (s*D c d+(1-s)*D d c) =
      s*D x (1-c)+(1-s)*D y d := by
  have hc' : 1-c ∈ Set.Ioo (0 : ℝ) 1 := ⟨by linarith [hc.2], by linarith [hc.1]⟩
  have hd' : 1-d ∈ Set.Ioo (0 : ℝ) 1 := ⟨by linarith [hd.2], by linarith [hd.1]⟩
  rw [reduction_D_expand x (1-d) hd', reduction_D_expand y c hc,
    reduction_D_expand c d hd, reduction_D_expand d c hc,
    reduction_D_expand x (1-c) hc', reduction_D_expand y d hd]
  simp only [sub_sub_cancel]
  linear_combination (-Real.log c + Real.log d + Real.log (1-c) - Real.log (1-d)) * hconstraint

/-- The swapped conditional laws minimize the entropy cost among every feasible
pair, including competitors on the boundary of the probability square. -/
theorem reduction_swap_minimizes {s c d x y : ℝ}
    (hs : s ∈ Set.Icc (0 : ℝ) 1)
    (hc : c ∈ Set.Ioo (0 : ℝ) 1) (hd : d ∈ Set.Ioo (0 : ℝ) 1)
    (hx : x ∈ Set.Icc (0 : ℝ) 1) (hy : y ∈ Set.Icc (0 : ℝ) 1)
    (hconstraint : s*x + (1-s)*y = s*(1-c)+(1-s)*d) :
    s*D c d+(1-s)*D d c ≤ s*D x (1-d)+(1-s)*D y c := by
  have hc' : 1-c ∈ Set.Ioo (0 : ℝ) 1 := ⟨by linarith [hc.2], by linarith [hc.1]⟩
  have h₁ := mul_nonneg hs.1 (reduction_D_nonneg hx hc')
  have h₂ := mul_nonneg (sub_nonneg.mpr hs.2) (reduction_D_nonneg hy hd)
  have he := reduction_swap_identity hc hd hconstraint
  linarith

end Auto
