/- Copyright (c) 2026 Joris Roos.
Released under Apache 2.0 license as described in the file LICENSE.
This file was automatically generated by Codex.
-/
import WeakHellinger.Auto.ThreePointInequality
import WeakHellinger.Auto.ReverseHypercontractivity

/-!
# Reduction of weak Hellinger to the three-point inequality

The actual `Auto.three_point_inequality` is imported from `ThreePointInequality.lean`.
The Mathlib-only `ReverseHypercontractivity` module supplies the entropy coefficient,
data processing, and the sharp noisy-cube bound. No additional axioms are used.

Source: the user's proposition `prop:three-point-implies-main` and weak Hellinger
`thm:main`. The main declaration is `Auto.weak_hellinger`; its finite sums encode
exactly the uniform noisy-cube expectations and conditional expectations.

-/

namespace Auto

open scoped BigOperators ENNReal

noncomputable section

/-- The binary mean appearing in the reduction equals `2q-1`. -/
theorem reduction_mean (s c d : ℝ) :
    s * ((1-d)-d) + (1-s) * (c-(1-c)) = 2 * q s c d - 1 := by
  unfold q
  ring

/-- The final algebraic step, once the channel estimate for `R` is proved. -/
theorem reduction_of_channel_bound {s c d ρ : ℝ}
    (hs : s ∈ Set.Icc (0 : ℝ) 1) (hc : c ∈ Set.Icc (0 : ℝ) 1)
    (hd : d ∈ Set.Icc (0 : ℝ) 1) (hchannel : Real.sqrt (1-ρ^2) ≤ R s c d) :
    r (s * ((1-d)-d) + (1-s) * (c-(1-c))) -
      (s * r ((1-d)-d) + (1-s) * r (c-(1-c))) ≤ 1-Real.sqrt (1-ρ^2) := by
  have h := three_point_inequality hs hc hd
  have hd' : r ((1-d)-d) = r (2*d-1) := by
    unfold r
    congr 1
    ring
  have hc' : c-(1-c) = 2*c-1 := by ring
  rw [reduction_mean, hd', hc']
  linarith

/-- Cross-entropy expansion, valid also at `x=0` and `x=1` with interior reference. -/
theorem reduction_D_expand (x v : ℝ) (hv : v ∈ Set.Ioo (0 : ℝ) 1) :
    D x v = x * Real.log x + (1-x) * Real.log (1-x) -
      x * Real.log v - (1-x) * Real.log (1-v) := by
  have hv0 : v ≠ 0 := ne_of_gt hv.1
  have hv1 : 1-v ≠ 0 := ne_of_gt (sub_pos.mpr hv.2)
  by_cases hx0 : x = 0
  · subst x
    simp [D]
  by_cases hx1 : 1-x = 0
  · have hx : x = 1 := by linarith
    subst x
    simp [D]
  unfold D
  rw [Real.log_div hx0 hv0, Real.log_div hx1 hv1]
  ring

/-- Nonnegativity of binary KL with an interior reference law. -/
theorem reduction_D_nonneg {x v : ℝ} (hx : x ∈ Set.Icc (0 : ℝ) 1)
    (hv : v ∈ Set.Ioo (0 : ℝ) 1) : 0 ≤ D x v := by
  by_cases hx0 : x = 0
  · subst x
    simp only [D, zero_div, zero_mul, sub_zero, one_mul, zero_add]
    exact Real.log_nonneg (by apply (le_div_iff₀ (sub_pos.mpr hv.2)).mpr; linarith [hv.1])
  by_cases hx1 : x = 1
  · subst x
    simp only [D, one_mul, sub_self, zero_div, zero_mul, add_zero]
    exact Real.log_nonneg ((le_div_iff₀ hv.1).mpr (by linarith [hv.2]))
  have hxp : 0 < x := lt_of_le_of_ne hx.1 (Ne.symm hx0)
  have hxm : 0 < 1-x := by have := lt_of_le_of_ne hx.2 hx1; linarith
  have h1 := mul_le_mul_of_nonneg_left
    (Real.log_le_sub_one_of_pos (div_pos hv.1 hxp)) hxp.le
  have h2 := mul_le_mul_of_nonneg_left
    (Real.log_le_sub_one_of_pos (div_pos (sub_pos.mpr hv.2) hxm)) hxm.le
  rw [Real.log_div (ne_of_gt hv.1) (ne_of_gt hxp)] at h1
  rw [Real.log_div (ne_of_gt (sub_pos.mpr hv.2)) (ne_of_gt hxm)] at h2
  have e1 : x * (v/x-1) = v-x := by field_simp
  have e2 : (1-x) * ((1-v)/(1-x)-1) = (1-v)-(1-x) := by field_simp
  rw [e1] at h1
  rw [e2] at h2
  rw [reduction_D_expand x v hv]
  nlinarith

/-- Complementing both Bernoulli laws preserves their divergence. -/
theorem reduction_D_complement (x v : ℝ) : D (1-x) (1-v) = D x v := by
  unfold D
  simp only [sub_sub_cancel]
  ring

/-- Exact Pythagorean identity for the swapped conditional laws.
The constraint eliminates the common log-odds multiplier. -/
theorem reduction_swap_identity {s c d x y : ℝ}
    (hc : c ∈ Set.Ioo (0 : ℝ) 1) (hd : d ∈ Set.Ioo (0 : ℝ) 1)
    (hconstraint : s*x + (1-s)*y = s*(1-c)+(1-s)*d) :
    s*D x (1-d)+(1-s)*D y c - (s*D c d+(1-s)*D d c) =
      s*D x (1-c)+(1-s)*D y d := by
  have hc' : 1-c ∈ Set.Ioo (0 : ℝ) 1 := ⟨by linarith [hc.2], by linarith [hc.1]⟩
  have hd' : 1-d ∈ Set.Ioo (0 : ℝ) 1 := ⟨by linarith [hd.2], by linarith [hd.1]⟩
  rw [reduction_D_expand x (1-d) hd', reduction_D_expand y c hc,
    reduction_D_expand c d hd, reduction_D_expand d c hc,
    reduction_D_expand x (1-c) hc', reduction_D_expand y d hd]
  simp only [sub_sub_cancel]
  linear_combination (-Real.log c + Real.log d + Real.log (1-c) - Real.log (1-d)) * hconstraint

/-- The swapped conditional laws minimize the entropy cost among every feasible
pair, including competitors on the boundary of the probability square. -/
theorem reduction_swap_minimizes {s c d x y : ℝ}
    (hs : s ∈ Set.Icc (0 : ℝ) 1)
    (hc : c ∈ Set.Ioo (0 : ℝ) 1) (hd : d ∈ Set.Ioo (0 : ℝ) 1)
    (hx : x ∈ Set.Icc (0 : ℝ) 1) (hy : y ∈ Set.Icc (0 : ℝ) 1)
    (hconstraint : s*x + (1-s)*y = s*(1-c)+(1-s)*d) :
    s*D c d+(1-s)*D d c ≤ s*D x (1-d)+(1-s)*D y c := by
  have hc' : 1-c ∈ Set.Ioo (0 : ℝ) 1 := ⟨by linarith [hc.2], by linarith [hc.1]⟩
  have h₁ := mul_nonneg hs.1 (reduction_D_nonneg hx hc')
  have h₂ := mul_nonneg (sub_nonneg.mpr hs.2) (reduction_D_nonneg hy hd)
  have he := reduction_swap_identity hc hd hconstraint
  linarith

/-- The binary table in the source: U=true has probability s; the two
conditional probabilities of V=true are 1-d and c. -/
def reductionLaw (s c d : ℝ) (hs : s ∈ Set.Icc (0 : ℝ) 1)
    (hc : c ∈ Set.Icc (0 : ℝ) 1) (hd : d ∈ Set.Icc (0 : ℝ) 1) :
    FiniteLaw (Bool × Bool) :=
  finiteJoint (bernoulliLaw s hs) (fun u => if u then
    bernoulliLaw (1-d) ⟨sub_nonneg.mpr hd.2, by linarith [hd.1]⟩ else bernoulliLaw c hc)

/-- Complementary masses of a Boolean law sum to one. -/
theorem reduction_bool_mass_false (μ : FiniteLaw Bool) : μ.mass false = 1-μ.mass true := by
  have h := μ.total
  simp only [Fintype.sum_bool] at h
  linarith

/-- A positive Boolean law gives an interior probability. -/
theorem reduction_bool_interior (μ : FiniteLaw Bool) (hμ : ∀ b, 0 < μ.mass b) (b : Bool) :
    μ.mass b ∈ Set.Ioo (0 : ℝ) 1 := by
  have h := μ.total
  simp only [Fintype.sum_bool] at h
  constructor
  · exact hμ b
  · cases b <;> linarith [hμ true,hμ false]

/-- Positive s,c,d give a positive joint table. -/
theorem reductionLaw_pos {s c d : ℝ} (hs : s ∈ Set.Ioo (0 : ℝ) 1)
    (hc : c ∈ Set.Ioo (0 : ℝ) 1) (hd : d ∈ Set.Ioo (0 : ℝ) 1) :
    ∀ z, 0 < (reductionLaw s c d ⟨hs.1.le,hs.2.le⟩ ⟨hc.1.le,hc.2.le⟩ ⟨hd.1.le,hd.2.le⟩).mass z := by
  rintro ⟨u,v⟩
  cases u <;> cases v <;> simp [reductionLaw, finiteJoint, bernoulliLaw] <;>
    exact mul_pos (by linarith [hs.1,hs.2]) (by linarith [hc.1,hc.2,hd.1,hd.2])

/-- The V marginal of the source table has parameter q. -/
theorem reductionLaw_second_true (s c d : ℝ) (hs hc hd) :
    (finiteSecond (reductionLaw s c d hs hc hd)).mass true = q s c d := by
  rw [finiteSecond_mass]
  simp [reductionLaw, finiteJoint, bernoulliLaw, q]

/-- The source table's mean is exactly 2q-1. -/
theorem reductionLaw_mean (s c d : ℝ) (hs hc hd) :
    finiteExpectation (reductionLaw s c d hs hc hd) (fun z => boolSign z.2) =
      2*q s c d-1 := by
  simp [finiteExpectation,reductionLaw,finiteJoint,bernoulliLaw,boolSign,
    Fintype.sum_prod_type,q]
  ring

/-- Conditional means for the positive table are the two means in the source. -/
theorem reductionLaw_conditional (s c d : ℝ) (hs : s ∈ Set.Ioo (0 : ℝ) 1) (hc hd) (u : Bool) :
    finiteConditionalMean (reductionLaw s c d ⟨hs.1.le,hs.2.le⟩ hc hd)
      (fun z => boolSign z.2) Prod.fst u = if u then 1-2*d else 2*c-1 := by
  classical
  have hs0 := hs.1.ne'
  have hs1 : 1-s ≠ 0 := (sub_pos.mpr hs.2).ne'
  cases u <;>
    simp [finiteConditionalMean,finiteMap,reductionLaw,finiteJoint,bernoulliLaw,
      boolSign,Fintype.sum_prod_type,Fintype.sum_bool] <;> field_simp <;> ring

/-- The conditional semicircle expectation is the weighted sum displayed in the source. -/
theorem reductionLaw_semicircle (s c d : ℝ) (hs : s ∈ Set.Ioo (0 : ℝ) 1) (hc hd) :
    conditionalSemicircle (reductionLaw s c d ⟨hs.1.le,hs.2.le⟩ hc hd)
      (fun z => boolSign z.2) Prod.fst = s*r (2*d-1)+(1-s)*r (2*c-1) := by
  have he (u : Bool) := reductionLaw_conditional s c d hs hc hd u
  change finiteExpectation (finiteFirst (reductionLaw s c d _ hc hd))
    (fun u => r (finiteConditionalMean (reductionLaw s c d _ hc hd)
      (fun z => boolSign z.2) Prod.fst u)) = _
  have hfirst := finiteFirst_joint (bernoulliLaw s ⟨hs.1.le,hs.2.le⟩)
    (fun u => if u then bernoulliLaw (1-d) ⟨sub_nonneg.mpr hd.2, by linarith [hd.1]⟩
      else bernoulliLaw c hc)
  change finiteFirst (reductionLaw s c d _ hc hd) = _ at hfirst
  rw [hfirst]
  unfold finiteExpectation
  simp only [Fintype.sum_bool]
  rw [he true,he false]
  simp only [bernoulliLaw, Bool.false_eq_true, ite_false, ite_true]
  have hr : r (1-2*d) = r (2*d-1) := by unfold r; congr 1; ring
  rw [hr]

/-- Every positive binary table is represented by exactly the source's s,c,d. -/
theorem reductionLaw_representation (μ : FiniteLaw (Bool × Bool)) (hμ : ∀ z, 0 < μ.mass z) :
    ∃ (s c d : ℝ) (hs : s ∈ Set.Ioo (0 : ℝ) 1)
      (hc : c ∈ Set.Ioo (0 : ℝ) 1) (hd : d ∈ Set.Ioo (0 : ℝ) 1),
      μ = reductionLaw s c d ⟨hs.1.le,hs.2.le⟩ ⟨hc.1.le,hc.2.le⟩ ⟨hd.1.le,hd.2.le⟩ := by
  let s := (finiteFirst μ).mass true
  let c := (finiteConditionalLaw μ false).mass true
  let d := (finiteConditionalLaw μ true).mass false
  have hs := reduction_bool_interior _ (finiteFirst_pos μ hμ) true
  have hc := reduction_bool_interior _ (finiteConditionalLaw_pos μ hμ false) true
  have hd := reduction_bool_interior _ (finiteConditionalLaw_pos μ hμ true) false
  refine ⟨s,c,d,hs,hc,hd,?_⟩
  rw [← finiteJoint_conditional μ]
  unfold reductionLaw
  congr 1
  · exact finiteLaw_bool_eq_bernoulli _
  · funext u
    cases u
    · exact finiteLaw_bool_eq_bernoulli _
    · apply finiteLaw_bool_ext
      change (finiteConditionalLaw μ true).mass true = 1-(finiteConditionalLaw μ true).mass false
      rw [reduction_bool_mass_false]
      ring

/-- Conditional means commute with recording the observed pair (g,f). -/
theorem reduction_conditional_map {α β γ : Type*} [Fintype α] [Fintype β] [Fintype γ]
    (μ : FiniteLaw α) (f : α → β) (g : α → γ) (v : β → ℝ) (u : γ) :
    finiteConditionalMean (finiteMap μ (fun z => (g z,f z))) (fun z => v z.2) Prod.fst u =
      finiteConditionalMean μ (v ∘ f) g u := by
  classical
  unfold finiteConditionalMean
  congr 1
  · have he := finiteExpectation_map μ (fun z => (g z,f z))
      (fun z => if z.1 = u then v z.2 else 0)
    simpa [finiteExpectation, mul_ite, Function.comp_def] using he
  · have he := finiteMap_comp μ (fun z => (g z,f z)) Prod.fst
    exact congrArg (fun ν => ν.mass u) he

/-- Both sides of the conditional expectation depend only on the joint output law. -/
theorem reduction_semicircle_map {α β γ : Type*} [Fintype α] [Fintype β] [Fintype γ]
    (μ : FiniteLaw α) (f : α → β) (g : α → γ) (v : β → ℝ) :
    conditionalSemicircle (finiteMap μ (fun z => (g z,f z))) (fun z => v z.2) Prod.fst =
      conditionalSemicircle μ (v ∘ f) g := by
  unfold conditionalSemicircle
  simp_rw [reduction_conditional_map]
  congr 1
  exact finiteMap_comp μ (fun z => (g z,f z)) Prod.fst

/-- Swapping the cube coordinates preserves its joint law. -/
theorem reduction_cube_swap (n : ℕ) (ρ : ℝ) (hρ) :
    finiteMap (cubeNoiseLaw n ρ hρ) Prod.swap = cubeNoiseLaw n ρ hρ := by
  have he := fun z => finiteMap_equiv_mass (cubeNoiseLaw n ρ hρ)
    (Equiv.prodComm (BooleanCube n) (BooleanCube n)) z
  ext z
  change (finiteMap (cubeNoiseLaw n ρ hρ) (Equiv.prodComm _ _)).mass z = _
  rw [he]
  exact congrArg (fun t => (Fintype.card (BooleanCube n) : ℝ)⁻¹*t)
    (cubeNoiseKernel_symm ρ z.2 z.1)

/-- Nonconstant Boolean functions are onto the two signs. -/
theorem reduction_bool_surjective {α : Type*} (f : α → Bool)
    (hf : ¬ ∃ b, ∀ x, f x = b) : Function.Surjective f := by
  intro b
  by_contra hb
  push Not at hb
  apply hf
  refine ⟨!b, fun x => ?_⟩
  have h := hb x
  cases b <;> cases hfx : f x <;> simp_all

/-- Data processing gives the rho² bound for nonconstant Boolean outputs. -/
theorem reduction_output_bound (n : ℕ) {ρ : ℝ} (hρ : ρ ∈ Set.Ioo (-1 : ℝ) 1)
    (f g : BooleanCube n → Bool) (hf : Function.Surjective f) (hg : Function.Surjective g) :
    sDagger (finiteMap (cubeNoiseLaw n ρ ⟨hρ.1.le,hρ.2.le⟩)
      (fun z => (g z.2,f z.1))) ≤ ρ^2 := by
  have hout := finiteMap_pos (cubeNoiseLaw n ρ ⟨hρ.1.le,hρ.2.le⟩)
    (cubeNoiseLaw_pos n hρ) (fun z => (g z.1,f z.2)) (hg.prodMap hf)
  have h := (sDagger_map_le _ (cubeNoiseLaw_pos n hρ) g f hout).trans
    (sDagger_cubeNoise_le n hρ)
  have he := finiteMap_comp (cubeNoiseLaw n ρ ⟨hρ.1.le,hρ.2.le⟩) Prod.swap
    (fun z => (g z.1,f z.2))
  have he2 := congrArg (fun μ => finiteMap μ (fun z => (g z.1,f z.2)))
    (reduction_cube_swap n ρ ⟨hρ.1.le,hρ.2.le⟩)
  convert! h using 1
  exact congrArg sDagger (he.symm.trans he2)

/-- Reconstruct any binary table from its first marginal and its conditional laws. -/
theorem reductionLaw_fixed_first (κ : FiniteLaw (Bool × Bool)) (s : ℝ) (hs)
    (hfirst : finiteFirst κ = bernoulliLaw s hs) :
    ∃ (c d : ℝ) (hc : c ∈ Set.Icc (0 : ℝ) 1) (hd : d ∈ Set.Icc (0 : ℝ) 1),
      κ = reductionLaw s c d hs hc hd := by
  let c := (finiteConditionalLaw κ false).mass true
  let d := (finiteConditionalLaw κ true).mass false
  have hc : c ∈ Set.Icc (0 : ℝ) 1 :=
    ⟨(finiteConditionalLaw κ false).nonneg true,finiteLaw_mass_le_one _ _⟩
  have hd : d ∈ Set.Icc (0 : ℝ) 1 :=
    ⟨(finiteConditionalLaw κ true).nonneg false,finiteLaw_mass_le_one _ _⟩
  refine ⟨c,d,hc,hd,?_⟩
  rw [← finiteJoint_conditional κ]
  unfold reductionLaw
  congr 1
  funext u
  cases u
  · exact finiteLaw_bool_eq_bernoulli _
  · apply finiteLaw_bool_ext
    change (finiteConditionalLaw κ true).mass true = 1-(finiteConditionalLaw κ true).mass false
    rw [reduction_bool_mass_false]
    ring

/-- Exact conditional entropy cost between two tables with the same U marginal. -/
theorem reductionLaw_KL {s c d : ℝ} (hs : s ∈ Set.Ioo (0 : ℝ) 1)
    (hc : c ∈ Set.Ioo (0 : ℝ) 1) (hd : d ∈ Set.Ioo (0 : ℝ) 1)
    (e f : ℝ) (he : e ∈ Set.Icc (0 : ℝ) 1) (hf : f ∈ Set.Icc (0 : ℝ) 1) :
    finiteKLReal (reductionLaw s e f ⟨hs.1.le,hs.2.le⟩ he hf)
      (reductionLaw s c d ⟨hs.1.le,hs.2.le⟩ ⟨hc.1.le,hc.2.le⟩ ⟨hd.1.le,hd.2.le⟩) =
      s*D f d+(1-s)*D e c := by
  unfold reductionLaw
  rw [finiteKLReal_joint]
  · rw [finiteKLReal_self,zero_add]
    simp only [Fintype.sum_bool,bernoulliLaw,Bool.false_eq_true,ite_true,ite_false,finiteKLReal]
    change s*finiteBinaryKL (1-f) (1-d)+(1-s)*finiteBinaryKL e c = _
    change s*D (1-f) (1-d)+(1-s)*D e c = _
    rw [reduction_D_complement]
  · intro u; cases u <;> simp [bernoulliLaw] <;> linarith [hs.1,hs.2]
  · intro u v; cases u <;> cases v <;> simp [bernoulliLaw] <;> linarith [hc.1,hc.2,hd.1,hd.2]

/-- The swapped table realizes the exact minimum defining the reverse coefficient. -/
theorem reduction_swap_transport {s c d : ℝ} (hs : s ∈ Set.Ioo (0 : ℝ) 1)
    (hc : c ∈ Set.Ioo (0 : ℝ) 1) (hd : d ∈ Set.Ioo (0 : ℝ) 1) :
    finiteTransportCost
      (reductionLaw s c d ⟨hs.1.le,hs.2.le⟩ ⟨hc.1.le,hc.2.le⟩ ⟨hd.1.le,hd.2.le⟩)
      (finiteSecond (reductionLaw s d c ⟨hs.1.le,hs.2.le⟩ ⟨hd.1.le,hd.2.le⟩ ⟨hc.1.le,hc.2.le⟩)) =
      ENNReal.ofReal (s*D c d+(1-s)*D d c) := by
  let μ := reductionLaw s c d ⟨hs.1.le,hs.2.le⟩ ⟨hc.1.le,hc.2.le⟩ ⟨hd.1.le,hd.2.le⟩
  let τ := reductionLaw s d c ⟨hs.1.le,hs.2.le⟩ ⟨hd.1.le,hd.2.le⟩ ⟨hc.1.le,hc.2.le⟩
  have hμ := reductionLaw_pos hs hc hd
  have hcost : finiteKL τ μ = ENNReal.ofReal (s*D c d+(1-s)*D d c) := by
    rw [finiteKL_of_supported _ _ (fun z hz => ((hμ z).ne' hz).elim)]
    exact congrArg ENNReal.ofReal (reductionLaw_KL hs hc hd d c _ _)
  have hfirst : finiteFirst τ = finiteFirst μ := by
    change finiteFirst (finiteJoint _ _) = finiteFirst (finiteJoint _ _)
    rw [finiteFirst_joint,finiteFirst_joint]
  apply le_antisymm ((finiteTransportCost_le μ τ (finiteSecond τ) ⟨hfirst,rfl⟩).trans_eq hcost)
  apply le_sInf
  rintro v ⟨κ,hκ,rfl⟩
  have hkfirst : finiteFirst κ = bernoulliLaw s ⟨hs.1.le,hs.2.le⟩ :=
    hκ.1.trans (finiteFirst_joint _ _)
  obtain ⟨e,f,he,hf,hrepr⟩ := reductionLaw_fixed_first κ s ⟨hs.1.le,hs.2.le⟩ hkfirst
  have hconstraint := congrArg (fun ν : FiniteLaw Bool => ν.mass true) hκ.2
  have hq : q s e f = q s d c := by
    convert! hconstraint using 1
    · rw [hrepr]; exact (reductionLaw_second_true s e f _ _ _).symm
    · exact (reductionLaw_second_true s d c _ _ _).symm
  rw [finiteKL_of_supported _ _ (fun z hz => ((hμ z).ne' hz).elim)]
  apply ENNReal.ofReal_le_ofReal
  have hkl : finiteKLReal κ μ = s*D f d+(1-s)*D e c := by
    rw [hrepr]
    exact reductionLaw_KL hs hc hd e f he hf
  rw [hkl]
  have h := reduction_swap_minimizes ⟨hs.1.le,hs.2.le⟩ hc hd
    (x := 1-f) (y := e) ⟨by linarith [hf.2],by linarith [hf.1]⟩ he hq
  rwa [reduction_D_complement] at h

/-- The two marginal parameters are interior, and differ by d-c. -/
theorem reduction_pq_interior {s c d : ℝ} (hs : s ∈ Set.Icc (0 : ℝ) 1)
    (hc : c ∈ Set.Ioo (0 : ℝ) 1) (hd : d ∈ Set.Ioo (0 : ℝ) 1) :
    p s c d ∈ Set.Ioo (0 : ℝ) 1 ∧ q s c d ∈ Set.Ioo (0 : ℝ) 1 := by
  have hmix {x y : ℝ} (hx : x ∈ Set.Ioo (0 : ℝ) 1) (hy : y ∈ Set.Ioo (0 : ℝ) 1) :
      s*x+(1-s)*y ∈ Set.Ioo (0 : ℝ) 1 := by
    constructor
    · nlinarith [mul_nonneg hs.1 hx.1.le,mul_nonneg (sub_nonneg.mpr hs.2) hy.1.le,
        mul_pos (by linarith : 0 < 1-s+s) hx.1,
        mul_nonneg hs.1 (sub_nonneg.mpr (min_le_left x y)),
        mul_nonneg (sub_nonneg.mpr hs.2) (sub_nonneg.mpr (min_le_right x y)),lt_min hx.1 hy.1]
    · have h := mul_nonneg hs.1 (sub_nonneg.mpr hx.2.le)
      have h' := mul_nonneg (sub_nonneg.mpr hs.2) (sub_nonneg.mpr hy.2.le)
      by_cases hzero : s=0
      · subst s; simpa using hy.2
      · have hp := mul_pos (lt_of_le_of_ne hs.1 (Ne.symm hzero)) (sub_pos.mpr hx.2)
        nlinarith
  exact ⟨hmix ⟨by linarith [hc.2],by linarith [hc.1]⟩ hd,
    hmix ⟨by linarith [hd.2],by linarith [hd.1]⟩ hc⟩

/-- Off the diagonal, the source's normalized R is exactly its divergence quotient. -/
theorem reduction_R_quotient {s c d : ℝ} (hs : s ∈ Set.Icc (0 : ℝ) 1)
    (hc : c ∈ Set.Ioo (0 : ℝ) 1) (hd : d ∈ Set.Ioo (0 : ℝ) 1) (hne : c ≠ d) :
    R s c d = Real.sqrt (D (p s c d) (q s c d)/(s*D c d+(1-s)*D d c)) := by
  have hpq := reduction_pq_interior hs hc hd
  have he : p s c d-q s c d = d-c := by unfold p q; ring
  have hpqne : p s c d ≠ q s c d := by intro h; apply hne; rw [h,sub_self] at he; linarith
  have hsq : (d-c)^2 = (c-d)^2 := by ring
  have hsqne : (c-d)^2 ≠ 0 := pow_ne_zero _ (sub_ne_zero.mpr hne)
  unfold R Rdenominator K
  simp only [hs,hc,hd,hpq.1,hpq.2,hs.1,hs.2,hc.1.le,hc.2.le,hd.1.le,hd.2.le,
    Set.mem_Icc,Set.mem_Ioo,and_self,ite_true,hne,Ne.symm hne,hpqne,ite_false,he,hsq]
  congr 1
  rw [← mul_div_assoc,← mul_div_assoc,← add_div]
  exact div_div_div_cancel_right₀ hsqne _ _

/-- The defining infimum bounds the explicit swapped-law quotient when c differs from d. -/
theorem reduction_complement_quotient {s c d : ℝ} (hs : s ∈ Set.Ioo (0 : ℝ) 1)
    (hc : c ∈ Set.Ioo (0 : ℝ) 1) (hd : d ∈ Set.Ioo (0 : ℝ) 1) (hne : c ≠ d) :
    1-sDagger (reductionLaw s c d ⟨hs.1.le,hs.2.le⟩ ⟨hc.1.le,hc.2.le⟩ ⟨hd.1.le,hd.2.le⟩) ≤
      D (p s c d) (q s c d)/(s*D c d+(1-s)*D d c) := by
  let μ := reductionLaw s c d ⟨hs.1.le,hs.2.le⟩ ⟨hc.1.le,hc.2.le⟩ ⟨hd.1.le,hd.2.le⟩
  let τ := reductionLaw s d c ⟨hs.1.le,hs.2.le⟩ ⟨hd.1.le,hd.2.le⟩ ⟨hc.1.le,hc.2.le⟩
  have hμ := reductionLaw_pos hs hc hd
  have hadm : reverseAdmissible μ (finiteSecond τ) := by
    apply reverseAdmissible_of_ne _ _ hμ
    intro he
    have he' := congrArg (fun ν : FiniteLaw Bool => ν.mass true) he
    have hq1 := reductionLaw_second_true s d c ⟨hs.1.le,hs.2.le⟩ ⟨hd.1.le,hd.2.le⟩ ⟨hc.1.le,hc.2.le⟩
    have hq2 := reductionLaw_second_true s c d ⟨hs.1.le,hs.2.le⟩ ⟨hc.1.le,hc.2.le⟩ ⟨hd.1.le,hd.2.le⟩
    have hq : q s d c = q s c d := hq1.symm.trans (he'.trans hq2)
    apply hne
    unfold q at hq
    nlinarith
  have hn : finiteKLReal (finiteSecond τ) (finiteSecond μ) = D (p s c d) (q s c d) := by
    rw [finiteLaw_bool_eq_bernoulli (finiteSecond τ),finiteLaw_bool_eq_bernoulli (finiteSecond μ)]
    trans finiteBinaryKL ((finiteSecond τ).mass true) ((finiteSecond μ).mass true)
    · convert! finiteKLReal_bernoulli
        ⟨(finiteSecond τ).nonneg true,finiteLaw_mass_le_one _ _⟩
        ⟨(finiteSecond μ).nonneg true,finiteLaw_mass_le_one _ _⟩ using 1
    have hq1 := reductionLaw_second_true s d c ⟨hs.1.le,hs.2.le⟩ ⟨hd.1.le,hd.2.le⟩ ⟨hc.1.le,hc.2.le⟩
    have hq2 := reductionLaw_second_true s c d ⟨hs.1.le,hs.2.le⟩ ⟨hc.1.le,hc.2.le⟩ ⟨hd.1.le,hd.2.le⟩
    change finiteBinaryKL ((finiteSecond τ).mass true) ((finiteSecond μ).mass true) = _
    rw [hq1,hq2]
    rfl
  have h := ENNReal.toReal_mono
    (ENNReal.div_ne_top (by rw [finiteKL_of_supported _ _ hadm.2]; exact ENNReal.ofReal_ne_top)
      (finiteTransportCost_pos _ _ hadm).ne') (reverseComplement_le_ratio μ (finiteSecond τ) hadm)
  rw [ENNReal.toReal_div,finiteKL_toReal _ _ hadm.2,hn] at h
  have hcst := reduction_swap_transport hs hc hd
  have hcst' : (finiteTransportCost μ (finiteSecond τ)).toReal = s*D c d+(1-s)*D d c := by
    rw [hcst,ENNReal.toReal_ofReal]
    exact add_nonneg (mul_nonneg hs.1.le (reduction_D_nonneg ⟨hc.1.le,hc.2.le⟩ hd))
      (mul_nonneg (by linarith [hs.2]) (reduction_D_nonneg ⟨hd.1.le,hd.2.le⟩ hc))
  rw [hcst'] at h
  simpa [sDagger] using h

/-- The three-point theorem yields weak Hellinger for every off-diagonal positive table. -/
theorem reduction_off_diagonal {s c d ρ : ℝ} (hs : s ∈ Set.Ioo (0 : ℝ) 1)
    (hc : c ∈ Set.Ioo (0 : ℝ) 1) (hd : d ∈ Set.Ioo (0 : ℝ) 1) (hne : c ≠ d)
    (hchannel : sDagger (reductionLaw s c d ⟨hs.1.le,hs.2.le⟩ ⟨hc.1.le,hc.2.le⟩ ⟨hd.1.le,hd.2.le⟩) ≤ ρ^2) :
    r (2*q s c d-1)-s*r (2*d-1)-(1-s)*r (2*c-1) ≤ 1-Real.sqrt (1-ρ^2) := by
  have hquot := reduction_complement_quotient hs hc hd hne
  have hr : Real.sqrt (1-ρ^2) ≤ R s c d := by
    rw [reduction_R_quotient ⟨hs.1.le,hs.2.le⟩ hc hd hne]
    exact Real.sqrt_le_sqrt (by linarith)
  have h := three_point_inequality ⟨hs.1.le,hs.2.le⟩ ⟨hc.1.le,hc.2.le⟩ ⟨hd.1.le,hd.2.le⟩
  linarith

/-- With probability epsilon resample V from a biased sign of probability 3/4. -/
def reductionPerturbation (ε : ℝ) (hε : ε ∈ Set.Icc (0 : ℝ) 1) (v : Bool) : FiniteLaw Bool :=
  bernoulliLaw (if v then 1-ε/4 else 3*ε/4) (by
    cases v <;> simp <;> constructor <;> linarith [hε.1,hε.2])

/-- Every transition of the perturbation is strictly positive when 0<epsilon<1. -/
theorem reductionPerturbation_pos {ε : ℝ} (hε : ε ∈ Set.Ioo (0 : ℝ) 1) (v w : Bool) :
    0 < (reductionPerturbation ε ⟨hε.1.le,hε.2.le⟩ v).mass w := by
  cases v <;> cases w <;> simp [reductionPerturbation,bernoulliLaw] <;> linarith [hε.1,hε.2]

/-- The perturbed conditional probabilities remain interior. -/
theorem reduction_perturbed_interior {x ε : ℝ} (hx : x ∈ Set.Ioo (0 : ℝ) 1)
    (hε : ε ∈ Set.Ioo (0 : ℝ) 1) (a : ℝ) (ha : a ∈ Set.Ioo (0 : ℝ) 1) :
    (1-ε)*x+a*ε ∈ Set.Ioo (0 : ℝ) 1 := by
  constructor
  · exact add_pos (mul_pos (sub_pos.mpr hε.2) hx.1) (mul_pos ha.1 hε.1)
  · nlinarith [mul_pos (sub_pos.mpr hε.2) (sub_pos.mpr hx.2),
      mul_pos hε.1 (sub_pos.mpr ha.2)]

/-- The perturbation changes c,d by different biases, breaking the diagonal. -/
theorem reduction_perturb_table {s c d ε : ℝ}
    (hs : s ∈ Set.Ioo (0 : ℝ) 1) (hc : c ∈ Set.Ioo (0 : ℝ) 1)
    (hd : d ∈ Set.Ioo (0 : ℝ) 1) (hε : ε ∈ Set.Ioo (0 : ℝ) 1) :
    finiteRightChannel
      (reductionLaw s c d ⟨hs.1.le,hs.2.le⟩ ⟨hc.1.le,hc.2.le⟩ ⟨hd.1.le,hd.2.le⟩)
      (reductionPerturbation ε ⟨hε.1.le,hε.2.le⟩) =
    reductionLaw s ((1-ε)*c+(3/4)*ε) ((1-ε)*d+(1/4)*ε) ⟨hs.1.le,hs.2.le⟩
      ⟨(reduction_perturbed_interior hc hε (3/4) (by constructor <;> norm_num)).1.le,
       (reduction_perturbed_interior hc hε (3/4) (by constructor <;> norm_num)).2.le⟩
      ⟨(reduction_perturbed_interior hd hε (1/4) (by constructor <;> norm_num)).1.le,
       (reduction_perturbed_interior hd hε (1/4) (by constructor <;> norm_num)).2.le⟩ := by
  classical
  ext ⟨u,v⟩
  cases u <;> cases v <;>
    simp [finiteRightChannel,finiteMap,finiteExtendRight,reductionLaw,finiteJoint,
      reductionPerturbation,bernoulliLaw,Fintype.sum_prod_type] <;> ring

/-- Weak Hellinger for a diagonal positive table, by stochastic perturbation and continuity. -/
theorem reduction_diagonal {s c ρ : ℝ} (hs : s ∈ Set.Ioo (0 : ℝ) 1)
    (hc : c ∈ Set.Ioo (0 : ℝ) 1)
    (hchannel : sDagger (reductionLaw s c c ⟨hs.1.le,hs.2.le⟩ ⟨hc.1.le,hc.2.le⟩ ⟨hc.1.le,hc.2.le⟩) ≤ ρ^2) :
    r (2*q s c c-1)-s*r (2*c-1)-(1-s)*r (2*c-1) ≤ 1-Real.sqrt (1-ρ^2) := by
  have hbound (ε : ℝ) (hε : ε ∈ Set.Ioo (0 : ℝ) 1) :
      r (2*q s ((1-ε)*c+(3/4)*ε) ((1-ε)*c+(1/4)*ε)-1)-
        s*r (2*((1-ε)*c+(1/4)*ε)-1)-(1-s)*r (2*((1-ε)*c+(3/4)*ε)-1) ≤
      1-Real.sqrt (1-ρ^2) := by
    have hcε := reduction_perturbed_interior hc hε (3/4) (by constructor <;> norm_num)
    have hdε := reduction_perturbed_interior hc hε (1/4) (by constructor <;> norm_num)
    have h := (sDagger_rightChannel_le _ _ (reductionLaw_pos hs hc hc)
      (reductionPerturbation_pos hε)).trans hchannel
    have he := congrArg sDagger (reduction_perturb_table hs hc hc hε)
    apply reduction_off_diagonal hs hcε hdε (by intro he; linarith [hε.1])
    convert! he ▸ h using 1
  have hcont : Continuous (fun ε : ℝ =>
      r (2*q s ((1-ε)*c+(3/4)*ε) ((1-ε)*c+(1/4)*ε)-1)-
        s*r (2*((1-ε)*c+(1/4)*ε)-1)-(1-s)*r (2*((1-ε)*c+(3/4)*ε)-1)) := by
    unfold r q
    fun_prop
  have ht := hcont.continuousAt.tendsto.mono_left
    (show nhdsWithin (0 : ℝ) (Set.Ioi 0) ≤ nhds 0 from nhdsWithin_le_nhds)
  have hb : ∀ᶠ ε in nhdsWithin (0 : ℝ) (Set.Ioi 0), ε ∈ Set.Ioo (0 : ℝ) 1 := by
    filter_upwards [self_mem_nhdsWithin, nhdsWithin_le_nhds (Iio_mem_nhds (by norm_num : (0 : ℝ) < 1))] with ε hε hε'
    exact ⟨hε,hε'⟩
  have h := le_of_tendsto ht (hb.mono fun ε hε => hbound ε hε)
  simpa using h

/-- Every positive binary law satisfies weak Hellinger at its channel bound. -/
theorem reduction_positive_law (μ : FiniteLaw (Bool × Bool)) (hμ : ∀ z, 0 < μ.mass z)
    (ρ : ℝ) (hchannel : sDagger μ ≤ ρ^2) :
    r (finiteExpectation μ (fun z => boolSign z.2)) -
      conditionalSemicircle μ (fun z => boolSign z.2) Prod.fst ≤ 1-Real.sqrt (1-ρ^2) := by
  obtain ⟨s,c,d,hs,hc,hd,he⟩ := reductionLaw_representation μ hμ
  subst μ
  have hm := reductionLaw_mean s c d ⟨hs.1.le,hs.2.le⟩ ⟨hc.1.le,hc.2.le⟩ ⟨hd.1.le,hd.2.le⟩
  have hec := reductionLaw_semicircle s c d hs ⟨hc.1.le,hc.2.le⟩ ⟨hd.1.le,hd.2.le⟩
  rw [hm,hec]
  have h : r (2*q s c d-1)-s*r (2*d-1)-(1-s)*r (2*c-1) ≤ 1-Real.sqrt (1-ρ^2) := by
    by_cases hcd : c=d
    · subst d; exact reduction_diagonal hs hc hchannel
    · exact reduction_off_diagonal hs hc hd hcd hchannel
  linarith

/-- The conditional semicircle expectation is nonnegative, including null fibers. -/
theorem reduction_semicircle_nonneg {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw α) (f : α → ℝ) (g : α → β) : 0 ≤ conditionalSemicircle μ f g := by
  exact Finset.sum_nonneg (fun b _ => mul_nonneg ((finiteMap μ g).nonneg b) (Real.sqrt_nonneg _))

/-- Every real semicircle value is at most one under Lean's real square-root convention. -/
theorem reduction_r_le_one (x : ℝ) : r x ≤ 1 := by
  unfold r
  exact (Real.sqrt_le_one).mpr (by nlinarith [sq_nonneg x])

/-- The endpoint correlations have right-hand side one, which always bounds the gap. -/
theorem reduction_endpoint {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw α) (f : α → ℝ) (g : α → β) {ρ : ℝ} (hρ : ρ = -1 ∨ ρ = 1) :
    r (finiteExpectation μ f)-conditionalSemicircle μ f g ≤ 1-Real.sqrt (1-ρ^2) := by
  have h := reduction_r_le_one (finiteExpectation μ f)
  have h' := reduction_semicircle_nonneg μ f g
  have he : Real.sqrt (1-ρ^2) = 0 := by rcases hρ with rfl | rfl <;> norm_num
  rw [he]
  linarith

/-- The desired right-hand side is nonnegative for every real correlation. -/
theorem reduction_rhs_nonneg (ρ : ℝ) : 0 ≤ 1-Real.sqrt (1-ρ^2) := by
  have h := reduction_r_le_one ρ
  exact sub_nonneg.mpr h

/-- A constant Boolean f has zero unconditional semicircle and a nonpositive gap. -/
theorem reduction_constant_f {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw α) (b : Bool) (g : α → β) (ρ : ℝ) :
    r (finiteExpectation μ (fun _ => boolSign b)) -
      conditionalSemicircle μ (fun _ => boolSign b) g ≤ 1-Real.sqrt (1-ρ^2) := by
  have he : finiteExpectation μ (fun _ => boolSign b) = boolSign b := by
    unfold finiteExpectation
    rw [← Finset.sum_mul, μ.total,one_mul]
  have hr : r (boolSign b) = 0 := by cases b <;> norm_num [r,boolSign]
  rw [he,hr]
  linarith [reduction_semicircle_nonneg μ (fun _ => boolSign b) g,reduction_rhs_nonneg ρ]

/-- With a constant observation the conditional mean equals the unconditional mean
on its only positive-mass fiber; all other fibers contribute zero. -/
theorem reduction_constant_g {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw α) (f : α → ℝ) (b : β) :
    conditionalSemicircle μ f (fun _ => b) = r (finiteExpectation μ f) := by
  classical
  have hm (u : β) : (finiteMap μ (fun _ => b)).mass u = if b=u then 1 else 0 := by
    by_cases he : b=u
    · simp [finiteMap,he,μ.total]
    · simp [finiteMap,he]
  have hc : finiteConditionalMean μ f (fun _ => b) b = finiteExpectation μ f := by
    simp [finiteConditionalMean,hm,finiteExpectation]
  unfold conditionalSemicircle finiteExpectation
  simp_rw [hm]
  simp only [ite_mul,one_mul,zero_mul]
  simp only [Finset.sum_ite_eq,Finset.mem_univ,ite_true,hc]
  rfl

/-- Weak Hellinger for a constant Boolean observation, with the null fibers explicit. -/
theorem reduction_constant_observation {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw α) (f : α → ℝ) (b : β) (ρ : ℝ) :
    r (finiteExpectation μ f)-conditionalSemicircle μ f (fun _ => b) ≤ 1-Real.sqrt (1-ρ^2) := by
  rw [reduction_constant_g,sub_self]
  exact reduction_rhs_nonneg ρ

/-- Weak Hellinger, source `thm:main`, for uniformly distributed rho-correlated
Boolean cubes. `true` denotes +1 and `false` denotes -1, so `boolSign ∘ f` and
`boolSign ∘ g` are exactly the source's sign-valued Boolean functions.
`cubeNoiseLaw` is the uniform independent-bit-flip joint law; `conditionalSemicircle`
is the finite expectation of sqrt(1-E[f(X)|g(Y)]²), with zero-mass fibers omitted
by their zero weight. No nonconstancy or nondegeneracy hypotheses are needed.
The proof actually includes the zero-dimensional cube as well. -/
theorem weak_hellinger (n : ℕ) (ρ : ℝ) (hρ : ρ ∈ Set.Icc (-1 : ℝ) 1)
    (f g : BooleanCube n → Bool) :
    Real.sqrt (1-(finiteExpectation (cubeNoiseLaw n ρ hρ) (fun z => boolSign (f z.1)))^2) -
      conditionalSemicircle (cubeNoiseLaw n ρ hρ) (fun z => boolSign (f z.1)) (fun z => g z.2) ≤
      1-Real.sqrt (1-ρ^2) := by
  classical
  change r (finiteExpectation _ _) - _ ≤ _
  by_cases hf : ∃ b, ∀ x, f x=b
  · obtain ⟨b,hb⟩ := hf
    have he : f = fun _ => b := funext hb
    subst f
    exact reduction_constant_f _ b _ ρ
  by_cases hg : ∃ b, ∀ y, g y=b
  · obtain ⟨b,hb⟩ := hg
    have he : g = fun _ => b := funext hb
    subst g
    exact reduction_constant_observation _ _ b ρ
  by_cases he : ρ=-1 ∨ ρ=1
  · exact reduction_endpoint _ _ _ he
  have hρ' : ρ ∈ Set.Ioo (-1 : ℝ) 1 := by
    constructor <;> rcases hρ with ⟨hl,hu⟩ <;> push Not at he <;> grind
  have hfs := reduction_bool_surjective f hf
  have hgs := reduction_bool_surjective g hg
  let μ := finiteMap (cubeNoiseLaw n ρ hρ) (fun z => (g z.2,f z.1))
  have hsurj : Function.Surjective (fun z : BooleanCube n × BooleanCube n => (g z.2,f z.1)) := by
    rintro ⟨u,v⟩
    obtain ⟨x,hx⟩ := hfs v
    obtain ⟨y,hy⟩ := hgs u
    exact ⟨(x,y),by simp [hx,hy]⟩
  have hμ : ∀ z, 0 < μ.mass z := finiteMap_pos _ (cubeNoiseLaw_pos n hρ') _ hsurj
  have hchannel : sDagger μ ≤ ρ^2 := reduction_output_bound n hρ' f g hfs hgs
  have h := reduction_positive_law μ hμ ρ hchannel
  have hm := finiteExpectation_map (cubeNoiseLaw n ρ hρ) (fun z => (g z.2,f z.1))
    (fun z => boolSign z.2)
  have hc := reduction_semicircle_map (cubeNoiseLaw n ρ hρ) (fun z => f z.1) (fun z => g z.2) boolSign
  change finiteExpectation μ (fun z => boolSign z.2) = _ at hm
  change conditionalSemicircle μ (fun z => boolSign z.2) Prod.fst = _ at hc
  rw [hm,hc] at h
  exact h

end

end Auto
