/- Copyright (c) 2026 Joris Roos.
Released under Apache 2.0 license as described in the file LICENSE.
This file was automatically generated by Codex.
-/
import Mathlib.Analysis.SpecialFunctions.Log.Deriv
import Mathlib.Analysis.SpecialFunctions.Log.NegMulLog
import Mathlib.Analysis.SpecialFunctions.Sqrt
import Mathlib.Analysis.SpecialFunctions.Sigmoid
import Mathlib.Analysis.Calculus.LHopital
import Mathlib.Algebra.BigOperators.Ring.Finset
import Mathlib.Basic.ENNReal.Real
import Mathlib.Tactic

/-!
# Finite reverse hypercontractivity for the weak Hellinger reduction

This file imports only Mathlib and introduces no additional axioms.
Finite probability laws are represented by their nonnegative, normalized atom masses.
The required proof order is recorded in `automation/Status.md`.
-/

namespace Auto

open scoped BigOperators ENNReal

noncomputable section

/-- A probability law on a finite alphabet, represented by its atom masses. -/
@[ext] structure FiniteLaw (α : Type*) [Fintype α] where
  mass : α → ℝ
  nonneg : ∀ a, 0 ≤ mass a
  total : ∑ a, mass a = 1

/-- Finite expectation with respect to an atom-mass probability law. -/
def finiteExpectation {α : Type*} [Fintype α] (μ : FiniteLaw α) (f : α → ℝ) : ℝ :=
  ∑ a, μ.mass a * f a

/-- The pushforward law under a map of finite alphabets. -/
noncomputable def finiteMap {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw α) (f : α → β) : FiniteLaw β := by
  classical
  exact {
    mass := fun b => ∑ a, if f a = b then μ.mass a else 0
    nonneg := fun b => Finset.sum_nonneg (fun a _ => by split_ifs; exact μ.nonneg a; rfl)
    total := by rw [Finset.sum_comm]; simpa using μ.total }

/-- Expectation under a pushforward is expectation of the composed function. -/
theorem finiteExpectation_map {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw α) (f : α → β) (g : β → ℝ) :
    finiteExpectation (finiteMap μ f) g = finiteExpectation μ (g ∘ f) := by
  classical
  unfold finiteExpectation finiteMap
  simp only
  simp_rw [Finset.sum_mul]
  rw [Finset.sum_comm]
  apply Finset.sum_congr rfl
  intro a _
  simp

/-- The real sign encoded by a Boolean value. -/
def boolSign (b : Bool) : ℝ := if b then 1 else -1

/-- The discrete cube; `true` encodes +1 and `false` encodes -1. -/
abbrev BooleanCube (n : ℕ) := Fin n → Bool

/-- Independent bit-flip transition probabilities with correlation `ρ`. -/
def cubeNoiseKernel {n : ℕ} (ρ : ℝ) (x y : BooleanCube n) : ℝ :=
  ∏ i, if x i = y i then (1+ρ)/2 else (1-ρ)/2

/-- Each row of the independent bit-flip kernel has total mass one. -/
theorem cubeNoiseKernel_sum {n : ℕ} (ρ : ℝ) (x : BooleanCube n) :
    ∑ y, cubeNoiseKernel ρ x y = 1 := by
  unfold cubeNoiseKernel
  rw [← Fintype.prod_sum (fun i (b : Bool) => if x i = b then (1+ρ)/2 else (1-ρ)/2)]
  apply Finset.prod_eq_one
  intro i _
  cases x i <;> simp <;> ring

/-- The bit-flip kernel is symmetric. -/
theorem cubeNoiseKernel_symm {n : ℕ} (ρ : ℝ) (x y : BooleanCube n) :
    cubeNoiseKernel ρ x y = cubeNoiseKernel ρ y x := by
  unfold cubeNoiseKernel
  apply Finset.prod_congr rfl
  intro i _
  simp only [eq_comm]

/-- Kernel masses are nonnegative for correlations in [-1,1]. -/
theorem cubeNoiseKernel_nonneg {n : ℕ} {ρ : ℝ}
    (hρ : ρ ∈ Set.Icc (-1 : ℝ) 1) (x y : BooleanCube n) :
    0 ≤ cubeNoiseKernel ρ x y := by
  apply Finset.prod_nonneg
  intro i _
  split_ifs <;> linarith [hρ.1, hρ.2]

/-- The uniform noisy-cube joint law: X is uniform and the bits of Y,
conditionally on X, are independently flipped with probability `(1-ρ)/2`. -/
noncomputable def cubeNoiseLaw (n : ℕ) (ρ : ℝ) (hρ : ρ ∈ Set.Icc (-1 : ℝ) 1) :
    FiniteLaw (BooleanCube n × BooleanCube n) where
  mass z := (Fintype.card (BooleanCube n) : ℝ)⁻¹ * cubeNoiseKernel ρ z.1 z.2
  nonneg z := mul_nonneg (inv_nonneg.mpr (Nat.cast_nonneg _)) (cubeNoiseKernel_nonneg hρ _ _)
  total := by
    rw [Fintype.sum_prod_type]
    simp_rw [← Finset.mul_sum, cubeNoiseKernel_sum]
    simp

/-- Both coordinates of the noisy-cube law are uniform: first marginal. -/
theorem cubeNoiseLaw_first (n : ℕ) (ρ : ℝ) (hρ : ρ ∈ Set.Icc (-1 : ℝ) 1)
    (x : BooleanCube n) :
    (finiteMap (cubeNoiseLaw n ρ hρ) Prod.fst).mass x =
      (Fintype.card (BooleanCube n) : ℝ)⁻¹ := by
  classical
  simp only [finiteMap, cubeNoiseLaw, Fintype.sum_prod_type]
  rw [Finset.sum_comm]
  simp only [Finset.sum_ite_eq', Finset.mem_univ, ite_true]
  rw [← Finset.mul_sum, cubeNoiseKernel_sum, mul_one]

/-- Both coordinates of the noisy-cube law are uniform: second marginal. -/
theorem cubeNoiseLaw_second (n : ℕ) (ρ : ℝ) (hρ : ρ ∈ Set.Icc (-1 : ℝ) 1)
    (y : BooleanCube n) :
    (finiteMap (cubeNoiseLaw n ρ hρ) Prod.snd).mass y =
      (Fintype.card (BooleanCube n) : ℝ)⁻¹ := by
  classical
  simp only [finiteMap, cubeNoiseLaw, Fintype.sum_prod_type]
  simp only [Finset.sum_ite_eq', Finset.mem_univ, ite_true]
  simp_rw [cubeNoiseKernel_symm ρ _ y]
  rw [← Finset.mul_sum, cubeNoiseKernel_sum, mul_one]

/-- Every atom of a finite probability law has mass at most one. -/
theorem finiteLaw_mass_le_one {α : Type*} [Fintype α] (μ : FiniteLaw α) (a : α) :
    μ.mass a ≤ 1 := by
  rw [← μ.total]
  exact Finset.single_le_sum (fun b _ => μ.nonneg b) (Finset.mem_univ a)

/-- The real KL sum, used when the first law is supported on the second.
Terms with zero first mass are zero, including when both masses vanish. -/
def finiteKLReal {α : Type*} [Fintype α] (ν μ : FiniteLaw α) : ℝ :=
  ∑ a, ν.mass a * Real.log (ν.mass a / μ.mass a)

/-- Finite-alphabet Kullback–Leibler divergence with its usual infinity convention.
It is infinite exactly when the first law gives positive mass to a zero-mass
atom of the reference law. On the supported domain the nonnegative KL sum
is embedded into the extended nonnegative reals. -/
def finiteKL {α : Type*} [Fintype α] (ν μ : FiniteLaw α) : ℝ≥0∞ := by
  classical
  exact if ∀ a, μ.mass a = 0 → ν.mass a = 0 then ENNReal.ofReal (finiteKLReal ν μ) else ⊤

/-- Conditional mean given a finite-valued observation. A zero-mass fiber
is assigned zero; it contributes zero to every expectation under the law. -/
noncomputable def finiteConditionalMean {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw α) (f : α → ℝ) (g : α → β) (b : β) : ℝ := by
  classical
  exact (∑ a, if g a = b then μ.mass a * f a else 0) / (finiteMap μ g).mass b

/-- Conditional semicircle expectation, expressed as its finite atom sum. -/
noncomputable def conditionalSemicircle {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw α) (f : α → ℝ) (g : α → β) : ℝ :=
  finiteExpectation (finiteMap μ g) (fun b => Real.sqrt (1 - finiteConditionalMean μ f g b ^ 2))

/-- The U marginal of a finite joint law of (U,V). -/
def finiteFirst {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) : FiniteLaw α := finiteMap μ Prod.fst

/-- The V marginal of a finite joint law of (U,V). -/
def finiteSecond {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) : FiniteLaw β := finiteMap μ Prod.snd

/-- A changed joint law with the original U marginal and prescribed V marginal.
This is the joint-law form of the conditional-law marginal constraint in the source. -/
def finiteTransportFeasible {α β : Type*} [Fintype α] [Fintype β]
    (μ κ : FiniteLaw (α × β)) (ν : FiniteLaw β) : Prop :=
  finiteFirst κ = finiteFirst μ ∧ finiteSecond κ = ν

/-- Minimum entropy cost of changing the V marginal while preserving the U marginal.
The KL chain rule identifies this with the source's infimum of the expected
conditional KL divergence. The infimum is taken in the extended nonnegative reals. -/
def finiteTransportCost {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) (ν : FiniteLaw β) : ℝ≥0∞ :=
  sInf {v | ∃ κ : FiniteLaw (α × β), finiteTransportFeasible μ κ ν ∧ v = finiteKL κ μ}

/-- Nontrivial changed V laws on the effective support of the reference marginal.
Restricting to this support avoids meaningless infinity/infinity ratios and is
equivalent to first deleting zero-probability letters from the alphabet. -/
def reverseAdmissible {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) (ν : FiniteLaw β) : Prop :=
  ν ≠ finiteSecond μ ∧ ∀ b, (finiteSecond μ).mass b = 0 → ν.mass b = 0

/-- The entropy formula for `1-s†(U;V)` on the effective support.
For a constant V there is no admissible changed law; the complement coefficient
is then one, so that s† is zero. The fraction is formed in the extended
nonnegative reals before the final real-valued coefficient is extracted. -/
def reverseComplement {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) : ℝ≥0∞ := by
  classical
  exact if ∃ ν, reverseAdmissible μ ν then
    sInf {v | ∃ ν : FiniteLaw β, reverseAdmissible μ ν ∧
      v = finiteKL ν (finiteSecond μ) / finiteTransportCost μ ν}
  else 1

/-- The reverse-hypercontractivity coefficient s† from the source's entropy formula. -/
def sDagger {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) : ℝ := 1 - (reverseComplement μ).toReal

/-- The defining complement identity; range and contraction properties are separate theorems. -/
theorem one_sub_sDagger {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) : 1 - sDagger μ = (reverseComplement μ).toReal := by
  unfold sDagger
  ring

/-- The coefficient is zero when there is no nontrivial changed marginal on its support. -/
theorem sDagger_of_no_admissible {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) (h : ¬ ∃ ν, reverseAdmissible μ ν) : sDagger μ = 0 := by
  simp [sDagger, reverseComplement, h]


/-- The elementary entropy tangent bound, including zero target mass. -/
theorem finiteKL_atom_lower {x y : ℝ} (hx : 0 ≤ x) (hy : 0 ≤ y)
    (hsupport : y = 0 → x = 0) : x-y ≤ x * Real.log (x/y) := by
  by_cases hx0 : x = 0
  · subst x
    simp only [zero_div, zero_mul, zero_sub]
    linarith
  have hxp : 0 < x := lt_of_le_of_ne hx (Ne.symm hx0)
  have hyp : 0 < y := lt_of_le_of_ne hy (Ne.symm (fun h => hx0 (hsupport h)))
  have h := mul_le_mul_of_nonneg_left (Real.log_le_sub_one_of_pos (div_pos hyp hxp)) hx
  rw [Real.log_div hyp.ne' hxp.ne'] at h
  have he : x * (y/x-1) = y-x := by field_simp
  rw [he] at h
  rw [Real.log_div hxp.ne' hyp.ne']
  nlinarith

/-- Gibbs' inequality for finite probability vectors on the supported domain. -/
theorem finiteKLReal_nonneg {α : Type*} [Fintype α] (ν μ : FiniteLaw α)
    (hsupport : ∀ a, μ.mass a = 0 → ν.mass a = 0) : 0 ≤ finiteKLReal ν μ := by
  have h := Finset.sum_le_sum (s := Finset.univ)
    (fun a _ => finiteKL_atom_lower (ν.nonneg a) (μ.nonneg a) (hsupport a))
  simpa [Finset.sum_sub_distrib, ν.total, μ.total, finiteKLReal] using h

/-- KL divergence vanishes for identical laws. -/
theorem finiteKLReal_self {α : Type*} [Fintype α] (μ : FiniteLaw α) :
    finiteKLReal μ μ = 0 := by
  simp [finiteKLReal]

/-- The extended divergence agrees with the real sum on its finite domain. -/
theorem finiteKL_of_supported {α : Type*} [Fintype α] (ν μ : FiniteLaw α)
    (hsupport : ∀ a, μ.mass a = 0 → ν.mass a = 0) :
    finiteKL ν μ = ENNReal.ofReal (finiteKLReal ν μ) := by
  exact ite_eq_left hsupport

/-- Extracting the real value of supported KL loses no information. -/
theorem finiteKL_toReal {α : Type*} [Fintype α] (ν μ : FiniteLaw α)
    (hsupport : ∀ a, μ.mass a = 0 → ν.mass a = 0) :
    (finiteKL ν μ).toReal = finiteKLReal ν μ := by
  rw [finiteKL_of_supported ν μ hsupport, ENNReal.toReal_ofReal (finiteKLReal_nonneg ν μ hsupport)]

/-- Finite KL vanishes at identical laws. -/
theorem finiteKL_self {α : Type*} [Fintype α] (μ : FiniteLaw α) : finiteKL μ μ = 0 := by
  simp [finiteKL, finiteKLReal_self]

/-- Cross-entropy expansion with a nonzero reference atom, including zero target mass. -/
theorem finiteKL_atom_expand (x : ℝ) {y : ℝ} (hy : y ≠ 0) :
    x * Real.log (x/y) = x * Real.log x - x * Real.log y := by
  by_cases hx : x = 0
  · simp [hx]
  rw [Real.log_div hx hy]
  ring

/-- Continuous finite KL sum as a function of the target vector for positive reference. -/
theorem continuous_finiteKL_sum {α : Type*} [Fintype α] (μ : α → ℝ)
    (hμ : ∀ a, 0 < μ a) :
    Continuous (fun v : α → ℝ => ∑ a, v a * Real.log (v a / μ a)) := by
  simp_rw [finiteKL_atom_expand _ (hμ _).ne']
  apply continuous_finsetSum
  intro a _
  exact ((Real.continuous_mul_log.comp (continuous_apply a)).sub
    ((continuous_apply a).mul_const _))

/-- A conditional kernel produces a normalized joint distribution. -/
def finiteJoint {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw α) (κ : α → FiniteLaw β) : FiniteLaw (α × β) where
  mass z := μ.mass z.1 * (κ z.1).mass z.2
  nonneg z := mul_nonneg (μ.nonneg _) ((κ _).nonneg _)
  total := by
    rw [Fintype.sum_prod_type]
    simp_rw [← Finset.mul_sum, (κ _).total]
    simpa using μ.total

/-- The joint law built from a kernel has the prescribed first marginal. -/
theorem finiteFirst_joint {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw α) (κ : α → FiniteLaw β) : finiteFirst (finiteJoint μ κ) = μ := by
  classical
  ext a
  simp only [finiteFirst, finiteMap, finiteJoint, Fintype.sum_prod_type]
  rw [Finset.sum_comm]
  simp only [Finset.sum_ite_eq', Finset.mem_univ, ite_true]
  rw [← Finset.mul_sum, (κ a).total, mul_one]

/-- Strictness of the entropy tangent bound away from equal atom masses. -/
theorem finiteKL_atom_strict {x y : ℝ} (hx : 0 ≤ x) (hy : 0 ≤ y)
    (hsupport : y = 0 → x = 0) (hne : x ≠ y) : x-y < x * Real.log (x/y) := by
  by_cases hx0 : x = 0
  · subst x
    simp only [zero_div, zero_mul, zero_sub]
    have : 0 < y := lt_of_le_of_ne hy hne
    linarith
  have hxp : 0 < x := lt_of_le_of_ne hx (Ne.symm hx0)
  have hyp : 0 < y := lt_of_le_of_ne hy (Ne.symm (fun h => hx0 (hsupport h)))
  have hne' : y/x ≠ 1 := by intro h; apply hne; exact ((div_eq_one_iff_eq hxp.ne').mp h).symm
  have h := mul_lt_mul_of_pos_left
    (Real.log_lt_sub_one_of_pos (div_pos hyp hxp) hne') hxp
  rw [Real.log_div hyp.ne' hxp.ne'] at h
  have he : x * (y/x-1) = y-x := by field_simp
  rw [he] at h
  rw [Real.log_div hxp.ne' hyp.ne']
  nlinarith

/-- Strict positivity of finite KL for distinct supported probability laws. -/
theorem finiteKLReal_pos {α : Type*} [Fintype α] (ν μ : FiniteLaw α)
    (hsupport : ∀ a, μ.mass a = 0 → ν.mass a = 0) (hne : ν ≠ μ) :
    0 < finiteKLReal ν μ := by
  classical
  have hex : ∃ a, ν.mass a ≠ μ.mass a := by
    by_contra! h
    apply hne
    ext a
    exact h a
  obtain ⟨a, ha⟩ := hex
  have h := Finset.sum_lt_sum (s := Finset.univ)
    (fun a _ => finiteKL_atom_lower (ν.nonneg a) (μ.nonneg a) (hsupport a))
    ⟨a, Finset.mem_univ a, finiteKL_atom_strict (ν.nonneg a) (μ.nonneg a) (hsupport a) ha⟩
  simpa [Finset.sum_sub_distrib, ν.total, μ.total, finiteKLReal] using h

/-- A nonnegative vector with zero total has every coordinate zero. -/
theorem finite_nonneg_eq_zero_of_sum_eq_zero {α : Type*} [Fintype α]
    (v : α → ℝ) (hv : ∀ a, 0 ≤ v a) (hs : ∑ a, v a = 0) (a : α) : v a = 0 := by
  have h := Finset.single_le_sum (fun b _ => hv b) (Finset.mem_univ a)
  rw [hs] at h
  exact le_antisymm h (hv a)

/-- Entropy tangent bound at an arbitrary positive ratio. -/
theorem finiteKL_atom_tangent {x y t : ℝ} (hx : 0 ≤ x) (hy : 0 ≤ y)
    (hsupport : y = 0 → x = 0) (ht : 0 < t) :
    x * Real.log t + x - y*t ≤ x * Real.log (x/y) := by
  by_cases hx0 : x = 0
  · subst x
    simp only [zero_mul, zero_add, zero_sub]
    exact neg_nonpos.mpr (mul_nonneg hy ht.le)
  have hxp : 0 < x := lt_of_le_of_ne hx (Ne.symm hx0)
  have hyp : 0 < y := lt_of_le_of_ne hy (Ne.symm (fun h => hx0 (hsupport h)))
  have h := finiteKL_atom_lower hx (mul_nonneg hy ht.le)
    (fun he => (mul_ne_zero hyp.ne' ht.ne' he).elim)
  rw [Real.log_div hxp.ne' (mul_ne_zero hyp.ne' ht.ne'), Real.log_mul hyp.ne' ht.ne'] at h
  rw [Real.log_div hxp.ne' hyp.ne']
  nlinarith

/-- Log-sum inequality for nonnegative finite vectors, including zero total mass. -/
theorem finite_log_sum {α : Type*} [Fintype α] (v w : α → ℝ)
    (hv : ∀ a, 0 ≤ v a) (hw : ∀ a, 0 ≤ w a)
    (hsupport : ∀ a, w a = 0 → v a = 0) :
    (∑ a, v a) * Real.log ((∑ a, v a)/(∑ a, w a)) ≤
      ∑ a, v a * Real.log (v a / w a) := by
  have hvsum : 0 ≤ ∑ a, v a := Finset.sum_nonneg (fun a _ => hv a)
  have hwsum : 0 ≤ ∑ a, w a := Finset.sum_nonneg (fun a _ => hw a)
  by_cases hv0 : ∑ a, v a = 0
  · have hz := finite_nonneg_eq_zero_of_sum_eq_zero v hv hv0
    simp [hz]
  have hvp : 0 < ∑ a, v a := lt_of_le_of_ne hvsum (Ne.symm hv0)
  have hw0 : (∑ a, w a) ≠ 0 := by
    intro he
    apply hv0
    have hz := finite_nonneg_eq_zero_of_sum_eq_zero w hw he
    exact Finset.sum_eq_zero (fun a _ => hsupport a (hz a))
  have hwp : 0 < ∑ a, w a := lt_of_le_of_ne hwsum (Ne.symm hw0)
  have ht := div_pos hvp hwp
  have h := Finset.sum_le_sum (s := Finset.univ)
    (fun a _ => finiteKL_atom_tangent (hv a) (hw a) (hsupport a) ht)
  simp only [Finset.sum_sub_distrib, Finset.sum_add_distrib, ← Finset.sum_mul] at h
  have he : (∑ a, w a) * ((∑ a, v a)/(∑ a, w a)) = ∑ a, v a := by field_simp
  rw [he] at h
  linarith

/-- A pushforward preserves absolute continuity on finite alphabets. -/
theorem finiteMap_supported {α β : Type*} [Fintype α] [Fintype β]
    (ν μ : FiniteLaw α) (f : α → β)
    (hsupport : ∀ a, μ.mass a = 0 → ν.mass a = 0) :
    ∀ b, (finiteMap μ f).mass b = 0 → (finiteMap ν f).mass b = 0 := by
  classical
  intro b hb
  have hz := finite_nonneg_eq_zero_of_sum_eq_zero
    (fun a => if f a = b then μ.mass a else 0)
    (fun a => by split_ifs; exact μ.nonneg a; rfl) hb
  apply Finset.sum_eq_zero
  intro a _
  split_ifs with he
  · exact hsupport a (by simpa [he] using hz a)
  · rfl

/-- Data processing for finite KL, proved by summing the log-sum inequality over fibers. -/
theorem finiteKLReal_map_le {α β : Type*} [Fintype α] [Fintype β]
    (ν μ : FiniteLaw α) (f : α → β)
    (hsupport : ∀ a, μ.mass a = 0 → ν.mass a = 0) :
    finiteKLReal (finiteMap ν f) (finiteMap μ f) ≤ finiteKLReal ν μ := by
  classical
  have hb (b : β) := finite_log_sum
    (fun a => if f a = b then ν.mass a else 0)
    (fun a => if f a = b then μ.mass a else 0)
    (fun a => by split_ifs; exact ν.nonneg a; rfl)
    (fun a => by split_ifs; exact μ.nonneg a; rfl)
    (fun a he => by split_ifs at * with h; exact hsupport a he; rfl)
  have h := Finset.sum_le_sum (s := Finset.univ) (fun b _ => hb b)
  change finiteKLReal (finiteMap ν f) (finiteMap μ f) ≤ _ at h
  refine h.trans_eq ?_
  rw [Finset.sum_comm]
  apply Finset.sum_congr rfl
  intro a _
  simp

/-- Extended-valued data processing for finite KL, including unsupported target laws. -/
theorem finiteKL_map_le {α β : Type*} [Fintype α] [Fintype β]
    (ν μ : FiniteLaw α) (f : α → β) : finiteKL (finiteMap ν f) (finiteMap μ f) ≤ finiteKL ν μ := by
  classical
  by_cases hs : ∀ a, μ.mass a = 0 → ν.mass a = 0
  · rw [finiteKL_of_supported ν μ hs,
      finiteKL_of_supported _ _ (finiteMap_supported ν μ f hs)]
    exact ENNReal.ofReal_le_ofReal (finiteKLReal_map_le ν μ f hs)
  · simp only [finiteKL, ite_eq_right hs]
    exact le_top

/-- The atomwise logarithm identity underlying the KL chain rule. -/
theorem finiteKL_atom_product (x y : ℝ) {u v : ℝ} (hu : u ≠ 0) (hv : v ≠ 0) :
    (x*y) * Real.log ((x*y)/(u*v)) =
      y * (x * Real.log (x/u)) + x * (y * Real.log (y/v)) := by
  by_cases hx : x = 0
  · simp [hx]
  by_cases hy : y = 0
  · simp [hy]
  rw [Real.log_div (mul_ne_zero hx hy) (mul_ne_zero hu hv),
    Real.log_mul hx hy, Real.log_mul hu hv, Real.log_div hx hu, Real.log_div hy hv]
  ring

/-- KL chain rule for two joint laws specified by marginal and conditional kernels. -/
theorem finiteKLReal_joint {α β : Type*} [Fintype α] [Fintype β]
    (ν μ : FiniteLaw α) (τ κ : α → FiniteLaw β)
    (hμ : ∀ a, 0 < μ.mass a) (hκ : ∀ a b, 0 < (κ a).mass b) :
    finiteKLReal (finiteJoint ν τ) (finiteJoint μ κ) = finiteKLReal ν μ +
      ∑ a, ν.mass a * finiteKLReal (τ a) (κ a) := by
  simp only [finiteKLReal, finiteJoint, Fintype.sum_prod_type]
  simp_rw [finiteKL_atom_product _ _ (hμ _).ne' (hκ _ _).ne']
  simp_rw [Finset.sum_add_distrib, ← Finset.sum_mul, ← Finset.mul_sum, (τ _).total, one_mul]

/-- The first marginal mass is a row sum of the joint probability table. -/
theorem finiteFirst_mass {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) (a : α) : (finiteFirst μ).mass a = ∑ b, μ.mass (a,b) := by
  classical
  simp only [finiteFirst, finiteMap, Fintype.sum_prod_type]
  rw [Finset.sum_comm]
  simp

/-- The second marginal mass is a column sum of the joint probability table. -/
theorem finiteSecond_mass {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) (b : β) : (finiteSecond μ).mass b = ∑ a, μ.mass (a,b) := by
  classical
  simp [finiteSecond, finiteMap, Fintype.sum_prod_type]

/-- Conditional probability table of V given U. On a null row, choose the V marginal;
the choice is immaterial because that row has zero probability. -/
def finiteConditionalLaw {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) (a : α) : FiniteLaw β := by
  classical
  exact if h : (finiteFirst μ).mass a = 0 then finiteSecond μ else {
    mass := fun b => μ.mass (a,b) / (finiteFirst μ).mass a
    nonneg := fun b => div_nonneg (μ.nonneg _) ((finiteFirst μ).nonneg a)
    total := by rw [← Finset.sum_div, ← finiteFirst_mass, div_self h] }

/-- Disintegration of a finite joint law into its first marginal and conditional law. -/
theorem finiteJoint_conditional {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) : finiteJoint (finiteFirst μ) (finiteConditionalLaw μ) = μ := by
  classical
  ext z
  obtain ⟨a,b⟩ := z
  by_cases h : (finiteFirst μ).mass a = 0
  · have hz : μ.mass (a,b) = 0 := finite_nonneg_eq_zero_of_sum_eq_zero
      (fun b => μ.mass (a,b)) (fun b => μ.nonneg _) (by rwa [← finiteFirst_mass]) b
    simp [finiteJoint, h, hz]
  · simp [finiteJoint, finiteConditionalLaw, h, mul_div_cancel₀]

/-- A finite probability law has a nonempty alphabet. -/
theorem finiteLaw_nonempty {α : Type*} [Fintype α] (μ : FiniteLaw α) : Nonempty α := by
  classical
  by_contra h
  have : IsEmpty α := not_nonempty_iff.mp h
  have := μ.total
  simp at this

/-- A positive joint reference table has a positive first marginal. -/
theorem finiteFirst_pos {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) (hμ : ∀ z, 0 < μ.mass z) (a : α) :
    0 < (finiteFirst μ).mass a := by
  obtain ⟨z⟩ := finiteLaw_nonempty μ
  rw [finiteFirst_mass]
  exact lt_of_lt_of_le (hμ (a,z.2))
    (Finset.single_le_sum (fun b _ => μ.nonneg _) (Finset.mem_univ _))

/-- Conditioning a positive joint reference table gives positive conditional masses. -/
theorem finiteConditionalLaw_pos {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) (hμ : ∀ z, 0 < μ.mass z) (a : α) (b : β) :
    0 < (finiteConditionalLaw μ a).mass b := by
  have h := finiteFirst_pos μ hμ a
  simp only [finiteConditionalLaw, dite_eq_right h.ne']
  exact div_pos (hμ _) h

/-- KL chain rule with actual conditional probabilities and a positive reference law. -/
theorem finiteKLReal_chain {α β : Type*} [Fintype α] [Fintype β]
    (ν μ : FiniteLaw (α × β)) (hμ : ∀ z, 0 < μ.mass z) :
    finiteKLReal ν μ = finiteKLReal (finiteFirst ν) (finiteFirst μ) +
      ∑ a, (finiteFirst ν).mass a *
        finiteKLReal (finiteConditionalLaw ν a) (finiteConditionalLaw μ a) := by
  have h := finiteKLReal_joint (finiteFirst ν) (finiteFirst μ)
    (finiteConditionalLaw ν) (finiteConditionalLaw μ)
    (finiteFirst_pos μ hμ) (finiteConditionalLaw_pos μ hμ)
  rwa [finiteJoint_conditional, finiteJoint_conditional] at h

/-- With fixed U marginal, joint KL is exactly the expected conditional KL cost
appearing in the source's definition of the reverse coefficient. -/
theorem finiteKLReal_fixed_first {α β : Type*} [Fintype α] [Fintype β]
    (ν μ : FiniteLaw (α × β)) (hμ : ∀ z, 0 < μ.mass z)
    (hfirst : finiteFirst ν = finiteFirst μ) :
    finiteKLReal ν μ = ∑ a, (finiteFirst μ).mass a *
      finiteKLReal (finiteConditionalLaw ν a) (finiteConditionalLaw μ a) := by
  rw [finiteKLReal_chain ν μ hμ, hfirst, finiteKLReal_self, zero_add]

/-- Probability tables with the prescribed row and column sums. -/
def finiteTransportPolytope {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) (ν : FiniteLaw β) : Set (α × β → ℝ) :=
  {w | (∀ z, 0 ≤ w z) ∧ (∀ a, ∑ b, w (a,b) = (finiteFirst μ).mass a) ∧
    ∀ b, ∑ a, w (a,b) = ν.mass b}

/-- The independent coupling is feasible for every prescribed second marginal. -/
theorem finiteTransportPolytope_nonempty {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) (ν : FiniteLaw β) :
    (finiteTransportPolytope μ ν).Nonempty := by
  refine ⟨fun z => (finiteFirst μ).mass z.1 * ν.mass z.2, ?_⟩
  refine ⟨fun z => mul_nonneg ((finiteFirst μ).nonneg _) (ν.nonneg _), ?_, ?_⟩
  · intro a
    dsimp
    rw [← Finset.mul_sum, ν.total, mul_one]
  · intro b
    dsimp
    rw [← Finset.sum_mul, (finiteFirst μ).total, one_mul]

/-- The marginal constraints and coordinate nonnegativity are closed conditions. -/
theorem finiteTransportPolytope_isClosed {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) (ν : FiniteLaw β) : IsClosed (finiteTransportPolytope μ ν) := by
  have h₀ : IsClosed {w : α × β → ℝ | ∀ z, 0 ≤ w z} :=
    by simpa only [Set.ofPred_forall] using
      isClosed_iInter (fun z => isClosed_le continuous_const (continuous_apply z))
  have h₁ : IsClosed {w : α × β → ℝ | ∀ a, ∑ b, w (a,b) = (finiteFirst μ).mass a} :=
    by simpa only [Set.ofPred_forall] using isClosed_iInter (fun a => isClosed_eq
      (continuous_finsetSum _ (fun b _ => continuous_apply (a,b))) continuous_const)
  have h₂ : IsClosed {w : α × β → ℝ | ∀ b, ∑ a, w (a,b) = ν.mass b} :=
    by simpa only [Set.ofPred_forall] using isClosed_iInter (fun b => isClosed_eq
      (continuous_finsetSum _ (fun a _ => continuous_apply (a,b))) continuous_const)
  exact h₀.inter (h₁.inter h₂)

/-- Every feasible table lies in the finite-dimensional unit cube. -/
theorem finiteTransportPolytope_subset_cube {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) (ν : FiniteLaw β) :
    finiteTransportPolytope μ ν ⊆ Set.Icc (0 : α × β → ℝ) 1 := by
  intro w hw
  refine ⟨hw.1, ?_⟩
  intro z
  have h := Finset.single_le_sum (fun b _ => hw.1 (z.1,b)) (Finset.mem_univ z.2)
  rw [hw.2.1 z.1] at h
  exact h.trans (finiteLaw_mass_le_one (finiteFirst μ) z.1)

/-- The entropy transportation polytope is compact. -/
theorem finiteTransportPolytope_isCompact {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) (ν : FiniteLaw β) : IsCompact (finiteTransportPolytope μ ν) :=
  isCompact_Icc.of_isClosed_subset (finiteTransportPolytope_isClosed μ ν)
    (finiteTransportPolytope_subset_cube μ ν)

/-- A feasible table defines a probability law. -/
def finiteLawOfTransportTable {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) (ν : FiniteLaw β) (w : α × β → ℝ)
    (hw : w ∈ finiteTransportPolytope μ ν) : FiniteLaw (α × β) where
  mass := w
  nonneg := hw.1
  total := by rw [Fintype.sum_prod_type]; simp_rw [hw.2.1]; exact (finiteFirst μ).total

/-- The probability law of a feasible table has the required marginals. -/
theorem finiteLawOfTransportTable_feasible {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) (ν : FiniteLaw β) (w : α × β → ℝ)
    (hw : w ∈ finiteTransportPolytope μ ν) :
    finiteTransportFeasible μ (finiteLawOfTransportTable μ ν w hw) ν := by
  constructor
  · ext a
    rw [finiteFirst_mass]
    exact hw.2.1 a
  · ext b
    rw [finiteSecond_mass]
    exact hw.2.2 b

/-- Every feasible probability law gives a point of the transportation polytope. -/
theorem finiteTransportFeasible_mem {α β : Type*} [Fintype α] [Fintype β]
    (μ κ : FiniteLaw (α × β)) (ν : FiniteLaw β)
    (hκ : finiteTransportFeasible μ κ ν) : κ.mass ∈ finiteTransportPolytope μ ν := by
  refine ⟨κ.nonneg, ?_, ?_⟩
  · intro a
    rw [← finiteFirst_mass, hκ.1]
  · intro b
    rw [← finiteSecond_mass, hκ.2]

/-- For a positive reference table, the entropy transportation infimum is attained. -/
theorem finiteTransport_minimizer {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) (ν : FiniteLaw β) (hμ : ∀ z, 0 < μ.mass z) :
    ∃ κ, finiteTransportFeasible μ κ ν ∧
      ∀ τ, finiteTransportFeasible μ τ ν → finiteKLReal κ μ ≤ finiteKLReal τ μ := by
  obtain ⟨w, hw, hmin⟩ := (finiteTransportPolytope_isCompact μ ν).exists_isMinOn
    (finiteTransportPolytope_nonempty μ ν) (continuous_finiteKL_sum μ.mass hμ).continuousOn
  refine ⟨finiteLawOfTransportTable μ ν w hw,
    finiteLawOfTransportTable_feasible μ ν w hw, ?_⟩
  intro τ hτ
  exact hmin (finiteTransportFeasible_mem μ τ ν hτ)

/-- The attained real minimum is also the extended-real entropy transportation cost. -/
theorem finiteTransportCost_attained {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) (ν : FiniteLaw β) (hμ : ∀ z, 0 < μ.mass z) :
    ∃ κ, finiteTransportFeasible μ κ ν ∧ finiteTransportCost μ ν = finiteKL κ μ := by
  obtain ⟨κ, hκ, hmin⟩ := finiteTransport_minimizer μ ν hμ
  refine ⟨κ, hκ, le_antisymm (sInf_le ⟨κ, hκ, rfl⟩) ?_⟩
  apply le_sInf
  rintro v ⟨τ, hτ, rfl⟩
  rw [finiteKL_of_supported κ μ (fun z hz => ((hμ z).ne' hz).elim),
    finiteKL_of_supported τ μ (fun z hz => ((hμ z).ne' hz).elim)]
  exact ENNReal.ofReal_le_ofReal (hmin τ hτ)

/-- Positive reference tables have finite entropy transportation cost. -/
theorem finiteTransportCost_ne_top {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) (ν : FiniteLaw β) (hμ : ∀ z, 0 < μ.mass z) :
    finiteTransportCost μ ν ≠ ⊤ := by
  obtain ⟨κ, _, he⟩ := finiteTransportCost_attained μ ν hμ
  rw [he, finiteKL_of_supported κ μ (fun z hz => ((hμ z).ne' hz).elim)]
  exact ENNReal.ofReal_ne_top

/-- Every joint entropy cost is at least the entropy cost of its prescribed V marginal. -/
theorem finiteKL_le_transportCost {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) (ν : FiniteLaw β) :
    finiteKL ν (finiteSecond μ) ≤ finiteTransportCost μ ν := by
  apply le_sInf
  rintro v ⟨κ, hκ, rfl⟩
  have h := finiteKL_map_le κ μ Prod.snd
  change finiteKL (finiteSecond κ) (finiteSecond μ) ≤ finiteKL κ μ at h
  rwa [hκ.2] at h

/-- Conditional KL cost for a changed kernel with the reference first marginal. -/
theorem finiteKLReal_changed_kernel {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) (τ : α → FiniteLaw β) (hμ : ∀ z, 0 < μ.mass z) :
    finiteKLReal (finiteJoint (finiteFirst μ) τ) μ =
      ∑ a, (finiteFirst μ).mass a * finiteKLReal (τ a) (finiteConditionalLaw μ a) := by
  have h := finiteKLReal_joint (finiteFirst μ) (finiteFirst μ) τ (finiteConditionalLaw μ)
    (finiteFirst_pos μ hμ) (finiteConditionalLaw_pos μ hμ)
  rwa [finiteJoint_conditional, finiteKLReal_self, zero_add] at h

/-- The entropy transportation cost is exactly the infimum in the source's
conditional-law program, for positive reference tables. -/
theorem finiteTransportCost_eq_conditional_inf {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) (ν : FiniteLaw β) (hμ : ∀ z, 0 < μ.mass z) :
    finiteTransportCost μ ν = sInf {v : ℝ≥0∞ | ∃ τ : α → FiniteLaw β,
      finiteSecond (finiteJoint (finiteFirst μ) τ) = ν ∧
      v = ENNReal.ofReal (∑ a, (finiteFirst μ).mass a *
        finiteKLReal (τ a) (finiteConditionalLaw μ a))} := by
  unfold finiteTransportCost
  congr 1
  ext v
  constructor
  · rintro ⟨κ, hκ, rfl⟩
    have hj : finiteJoint (finiteFirst μ) (finiteConditionalLaw κ) = κ := by
      rw [← hκ.1, finiteJoint_conditional]
    refine ⟨finiteConditionalLaw κ, by rw [hj]; exact hκ.2, ?_⟩
    rw [finiteKL_of_supported κ μ (fun z hz => ((hμ z).ne' hz).elim),
      finiteKLReal_fixed_first κ μ hμ hκ.1]
  · rintro ⟨τ, hτ, rfl⟩
    refine ⟨finiteJoint (finiteFirst μ) τ, ⟨finiteFirst_joint _ _, hτ⟩, ?_⟩
    rw [finiteKL_of_supported _ μ (fun z hz => ((hμ z).ne' hz).elim),
      finiteKLReal_changed_kernel μ τ hμ]

/-- The reference law itself has zero transportation cost. -/
theorem finiteTransportCost_self {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) : finiteTransportCost μ (finiteSecond μ) = 0 := by
  apply le_antisymm _ bot_le
  have h : finiteTransportCost μ (finiteSecond μ) ≤ finiteKL μ μ := sInf_le ⟨μ, ⟨rfl, rfl⟩, rfl⟩
  exact h.trans_eq (finiteKL_self μ)

/-- Every feasible joint law bounds the transportation cost from above. -/
theorem finiteTransportCost_le {α β : Type*} [Fintype α] [Fintype β]
    (μ κ : FiniteLaw (α × β)) (ν : FiniteLaw β)
    (hκ : finiteTransportFeasible μ κ ν) : finiteTransportCost μ ν ≤ finiteKL κ μ :=
  sInf_le ⟨κ, hκ, rfl⟩

/-- The defining infimum is at most any admissible entropy ratio. -/
theorem reverseComplement_le_ratio {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) (ν : FiniteLaw β) (hν : reverseAdmissible μ ν) :
    reverseComplement μ ≤ finiteKL ν (finiteSecond μ) / finiteTransportCost μ ν := by
  classical
  unfold reverseComplement
  rw [ite_eq_left ⟨ν, hν⟩]
  exact sInf_le ⟨ν, hν, rfl⟩

/-- The reverse complement belongs to [0,1], including degenerate alphabets. -/
theorem reverseComplement_le_one {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) : reverseComplement μ ≤ 1 := by
  classical
  by_cases h : ∃ ν, reverseAdmissible μ ν
  · obtain ⟨ν, hν⟩ := h
    apply (reverseComplement_le_ratio μ ν hν).trans
    exact ENNReal.div_le_of_le_mul (by simpa using finiteKL_le_transportCost μ ν)
  · simp [reverseComplement, h]

/-- The reverse coefficient really is a number in [0,1]. -/
theorem sDagger_mem_Icc {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) : sDagger μ ∈ Set.Icc (0 : ℝ) 1 := by
  have h := ENNReal.toReal_mono (by simp : (1 : ℝ≥0∞) ≠ ⊤) (reverseComplement_le_one μ)
  have h0 := ENNReal.toReal_nonneg (a := reverseComplement μ)
  simp only [ENNReal.toReal_one] at h
  unfold sDagger
  constructor <;> linarith

/-- A positive joint law has a positive second marginal. -/
theorem finiteSecond_pos {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) (hμ : ∀ z, 0 < μ.mass z) (b : β) :
    0 < (finiteSecond μ).mass b := by
  obtain ⟨z⟩ := finiteLaw_nonempty μ
  rw [finiteSecond_mass]
  exact lt_of_lt_of_le (hμ (z.1,b))
    (Finset.single_le_sum (fun a _ => μ.nonneg (a,b)) (Finset.mem_univ z.1))

/-- Positive references make every distinct second-marginal law admissible. -/
theorem reverseAdmissible_of_ne {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) (ν : FiniteLaw β) (hμ : ∀ z, 0 < μ.mass z)
    (hne : ν ≠ finiteSecond μ) : reverseAdmissible μ ν :=
  ⟨hne, fun b hb => ((finiteSecond_pos μ hμ b).ne' hb).elim⟩

/-- A distinct changed marginal has strictly positive transportation cost. -/
theorem finiteTransportCost_pos {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) (ν : FiniteLaw β) (hν : reverseAdmissible μ ν) :
    0 < finiteTransportCost μ ν := by
  have hp := finiteKLReal_pos ν (finiteSecond μ) hν.2 hν.1
  have he := finiteKL_of_supported ν (finiteSecond μ) hν.2
  apply lt_of_lt_of_le _ (finiteKL_le_transportCost μ ν)
  rw [he]
  exact ENNReal.ofReal_pos.mpr hp

/-- Entropy lifting: every changed V law can be coupled to the original U marginal
at joint entropy cost at most `1/a` times its marginal entropy cost. The
multiplicative form also makes sense for `a=0`. -/
def EntropyLifting {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) (a : ℝ) : Prop :=
  ∀ ν : FiniteLaw β, ∃ κ : FiniteLaw (α × β), finiteTransportFeasible μ κ ν ∧
    a * finiteKLReal κ μ ≤ finiteKLReal ν (finiteSecond μ)

/-- Entropy lifting bounds the reverse complement from below. -/
theorem reverseComplement_ge_of_lifting {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) (hμ : ∀ z, 0 < μ.mass z) {a : ℝ}
    (ha : a ∈ Set.Icc (0 : ℝ) 1) (hlift : EntropyLifting μ a) :
    ENNReal.ofReal a ≤ reverseComplement μ := by
  classical
  unfold reverseComplement
  split_ifs with hex
  · apply le_sInf
    rintro v ⟨ν, hν, rfl⟩
    obtain ⟨κ, hκ, hcost⟩ := hlift ν
    apply (ENNReal.le_div_iff_mul_le (Or.inl (finiteTransportCost_pos μ ν hν).ne')
      (Or.inl (finiteTransportCost_ne_top μ ν hμ))).mpr
    apply (mul_le_mul' (le_refl (ENNReal.ofReal a)) (finiteTransportCost_le μ κ ν hκ)).trans
    rw [finiteKL_of_supported κ μ (fun z hz => ((hμ z).ne' hz).elim),
      finiteKL_of_supported ν (finiteSecond μ) hν.2, ← ENNReal.ofReal_mul ha.1]
    exact ENNReal.ofReal_le_ofReal hcost
  · exact ENNReal.ofReal_le_one.mpr ha.2

/-- The reverse complement bound yields an entropy lift via the attained minimum. -/
theorem entropyLifting_of_reverseComplement {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) (hμ : ∀ z, 0 < μ.mass z) {a : ℝ}
    (ha : 0 ≤ a) (hbound : ENNReal.ofReal a ≤ reverseComplement μ) : EntropyLifting μ a := by
  intro ν
  by_cases he : ν = finiteSecond μ
  · subst ν
    exact ⟨μ, ⟨rfl, rfl⟩, by rw [finiteKLReal_self, finiteKLReal_self]; simp⟩
  have hν := reverseAdmissible_of_ne μ ν hμ he
  obtain ⟨κ, hκ, hcost⟩ := finiteTransportCost_attained μ ν hμ
  refine ⟨κ, hκ, ?_⟩
  have h := hbound.trans (reverseComplement_le_ratio μ ν hν)
  rw [ENNReal.le_div_iff_mul_le (Or.inl (finiteTransportCost_pos μ ν hν).ne')
    (Or.inl (finiteTransportCost_ne_top μ ν hμ))] at h
  rw [hcost, finiteKL_of_supported κ μ (fun z hz => ((hμ z).ne' hz).elim),
    finiteKL_of_supported ν (finiteSecond μ) hν.2, ← ENNReal.ofReal_mul ha] at h
  exact (ENNReal.ofReal_le_ofReal_iff (finiteKLReal_nonneg ν (finiteSecond μ) hν.2)).mp h

/-- Exact entropy-lifting characterization of the reverse coefficient for positive tables. -/
theorem entropyLifting_iff {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) (hμ : ∀ z, 0 < μ.mass z) {a : ℝ}
    (ha : a ∈ Set.Icc (0 : ℝ) 1) :
    EntropyLifting μ a ↔ ENNReal.ofReal a ≤ reverseComplement μ :=
  ⟨reverseComplement_ge_of_lifting μ hμ ha, entropyLifting_of_reverseComplement μ hμ ha.1⟩

/-- Composition of finite pushforwards. -/
theorem finiteMap_comp {α β γ : Type*} [Fintype α] [Fintype β] [Fintype γ]
    (μ : FiniteLaw α) (f : α → β) (g : β → γ) :
    finiteMap (finiteMap μ f) g = finiteMap μ (g ∘ f) := by
  classical
  ext c
  simp only [finiteMap]
  simp_rw [Finset.ite_sum_zero]
  rw [Finset.sum_comm]
  apply Finset.sum_congr rfl
  intro a _
  calc
    _ = ∑ b, if f a = b then (if g b = c then μ.mass a else 0) else 0 := by
      apply Finset.sum_congr rfl
      intro b _
      split_ifs <;> rfl
    _ = _ := by simp

/-- The first marginal commutes with separate maps of the two coordinates. -/
theorem finiteFirst_map_pair {α β γ δ : Type*} [Fintype α] [Fintype β]
    [Fintype γ] [Fintype δ] (μ : FiniteLaw (α × β)) (f : α → γ) (g : β → δ) :
    finiteFirst (finiteMap μ (fun z => (f z.1, g z.2))) = finiteMap (finiteFirst μ) f := by
  unfold finiteFirst
  rw [finiteMap_comp, finiteMap_comp]
  rfl

/-- The second marginal commutes with separate maps of the two coordinates. -/
theorem finiteSecond_map_pair {α β γ δ : Type*} [Fintype α] [Fintype β]
    [Fintype γ] [Fintype δ] (μ : FiniteLaw (α × β)) (f : α → γ) (g : β → δ) :
    finiteSecond (finiteMap μ (fun z => (f z.1, g z.2))) = finiteMap (finiteSecond μ) g := by
  unfold finiteSecond
  rw [finiteMap_comp, finiteMap_comp]
  rfl

/-- Lift a changed output law using the reference law's conditional distribution
on each fiber of a deterministic observation. -/
def finiteLiftOutput {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw α) (f : α → β) (ν : FiniteLaw β)
    (hpos : ∀ b, 0 < (finiteMap μ f).mass b) : FiniteLaw α where
  mass a := μ.mass a * (ν.mass (f a) / (finiteMap μ f).mass (f a))
  nonneg a := mul_nonneg (μ.nonneg a) (div_nonneg (ν.nonneg _) (hpos _).le)
  total := by
    have h := finiteExpectation_map μ f (fun b => ν.mass b / (finiteMap μ f).mass b)
    dsimp [finiteExpectation, Function.comp_def] at h
    rw [← h]
    have he (b : β) : (finiteMap μ f).mass b * (ν.mass b / (finiteMap μ f).mass b) = ν.mass b := by
      field_simp [(hpos b).ne']
    simp_rw [he]
    exact ν.total

/-- The lifted law has exactly the prescribed output marginal. -/
theorem finiteLiftOutput_map {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw α) (f : α → β) (ν : FiniteLaw β)
    (hpos : ∀ b, 0 < (finiteMap μ f).mass b) :
    finiteMap (finiteLiftOutput μ f ν hpos) f = ν := by
  classical
  ext b
  change (∑ a, if f a = b then μ.mass a *
    (ν.mass (f a) / (finiteMap μ f).mass (f a)) else 0) = ν.mass b
  calc
    _ = ∑ a, (if f a = b then μ.mass a else 0) *
        (ν.mass b / (finiteMap μ f).mass b) := by
      apply Finset.sum_congr rfl
      intro a _
      split_ifs with he <;> simp [he]
    _ = (finiteMap μ f).mass b * (ν.mass b / (finiteMap μ f).mass b) := by
      rw [← Finset.sum_mul]
      rfl
    _ = ν.mass b := by field_simp [(hpos b).ne']

/-- The reference-conditional lift has exactly the KL cost of the changed output law. -/
theorem finiteLiftOutput_KL {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw α) (f : α → β) (ν : FiniteLaw β)
    (hμ : ∀ a, 0 < μ.mass a) (hpos : ∀ b, 0 < (finiteMap μ f).mass b) :
    finiteKLReal (finiteLiftOutput μ f ν hpos) μ = finiteKLReal ν (finiteMap μ f) := by
  have he (a : α) :
      (finiteLiftOutput μ f ν hpos).mass a *
        Real.log ((finiteLiftOutput μ f ν hpos).mass a / μ.mass a) =
      μ.mass a * ((ν.mass (f a) / (finiteMap μ f).mass (f a)) *
        Real.log (ν.mass (f a) / (finiteMap μ f).mass (f a))) := by
    dsimp [finiteLiftOutput]
    rw [mul_div_cancel_left₀ _ (hμ a).ne']
    ring
  unfold finiteKLReal
  simp_rw [he]
  have h := finiteExpectation_map μ f
    (fun b => (ν.mass b / (finiteMap μ f).mass b) * Real.log (ν.mass b / (finiteMap μ f).mass b))
  dsimp [finiteExpectation, Function.comp_def] at h
  rw [← h]
  apply Finset.sum_congr rfl
  intro b _
  have hc : (finiteMap μ f).mass b * (ν.mass b / (finiteMap μ f).mass b) = ν.mass b := by field_simp [(hpos b).ne']
  rw [← mul_assoc, hc]

/-- Entropy lifting survives deterministic processing on either side. -/
theorem entropyLifting_map {α β γ δ : Type*} [Fintype α] [Fintype β]
    [Fintype γ] [Fintype δ] (μ : FiniteLaw (α × β)) (hμ : ∀ z, 0 < μ.mass z)
    (f : α → γ) (g : β → δ) (hg : ∀ d, 0 < (finiteMap (finiteSecond μ) g).mass d)
    {a : ℝ} (ha : 0 ≤ a) (hlift : EntropyLifting μ a) :
    EntropyLifting (finiteMap μ (fun z => (f z.1, g z.2))) a := by
  intro ν
  let ν' := finiteLiftOutput (finiteSecond μ) g ν hg
  obtain ⟨κ, hκ, hc⟩ := hlift ν'
  refine ⟨finiteMap κ (fun z => (f z.1, g z.2)), ⟨?_, ?_⟩, ?_⟩
  · rw [finiteFirst_map_pair, finiteFirst_map_pair, hκ.1]
  · rw [finiteSecond_map_pair, hκ.2]
    exact finiteLiftOutput_map _ _ _ _
  · have hKL := finiteKLReal_map_le κ μ (fun z => (f z.1, g z.2))
      (fun z hz => ((hμ z).ne' hz).elim)
    have h := (mul_le_mul_of_nonneg_left hKL ha).trans hc
    rw [finiteSecond_map_pair]
    exact h.trans_eq (finiteLiftOutput_KL _ _ _ (finiteSecond_pos μ hμ) hg)

/-- Data processing for s† under deterministic functions, on positive reference tables
and positive output tables (zero-probability output letters may be deleted first). -/
theorem sDagger_map_le {α β γ δ : Type*} [Fintype α] [Fintype β]
    [Fintype γ] [Fintype δ] (μ : FiniteLaw (α × β)) (hμ : ∀ z, 0 < μ.mass z)
    (f : α → γ) (g : β → δ)
    (hout : ∀ z, 0 < (finiteMap μ (fun z => (f z.1, g z.2))).mass z) :
    sDagger (finiteMap μ (fun z => (f z.1, g z.2))) ≤ sDagger μ := by
  let a := (reverseComplement μ).toReal
  have hfin : reverseComplement μ ≠ ⊤ := ne_top_of_le_ne_top (by simp) (reverseComplement_le_one μ)
  have ha : a ∈ Set.Icc (0 : ℝ) 1 := by
    refine ⟨ENNReal.toReal_nonneg, ?_⟩
    have h := ENNReal.toReal_mono (by simp : (1 : ℝ≥0∞) ≠ ⊤) (reverseComplement_le_one μ)
    simpa [a] using h
  have hbase : EntropyLifting μ a := entropyLifting_of_reverseComplement μ hμ ha.1
    (by simp [a, ENNReal.ofReal_toReal, hfin])
  have hg : ∀ d, 0 < (finiteMap (finiteSecond μ) g).mass d := by
    intro d
    rw [← finiteSecond_map_pair μ f g]
    exact finiteSecond_pos _ hout d
  have houtLift := entropyLifting_map μ hμ f g hg ha.1 hbase
  have h := reverseComplement_ge_of_lifting _ hout ha houtLift
  have houtfin : reverseComplement (finiteMap μ (fun z => (f z.1, g z.2))) ≠ ⊤ :=
    ne_top_of_le_ne_top (by simp) (reverseComplement_le_one _)
  have hreal := ENNReal.toReal_mono houtfin h
  rw [ENNReal.toReal_ofReal ha.1] at hreal
  unfold sDagger
  dsimp [a] at hreal
  linarith

/-- Append an independent conditional output W to the V coordinate of (U,V). -/
def finiteExtendRight {α β γ : Type*} [Fintype α] [Fintype β] [Fintype γ]
    (μ : FiniteLaw (α × β)) (κ : β → FiniteLaw γ) : FiniteLaw (α × (β × γ)) where
  mass z := μ.mass (z.1,z.2.1) * (κ z.2.1).mass z.2.2
  nonneg z := mul_nonneg (μ.nonneg _) ((κ _).nonneg _)
  total := by
    simp only [Fintype.sum_prod_type]
    simp_rw [← Finset.mul_sum, (κ _).total]
    simpa [Fintype.sum_prod_type] using μ.total

/-- Adding a conditional output preserves the U marginal. -/
theorem finiteFirst_extendRight {α β γ : Type*} [Fintype α] [Fintype β] [Fintype γ]
    (μ : FiniteLaw (α × β)) (κ : β → FiniteLaw γ) :
    finiteFirst (finiteExtendRight μ κ) = finiteFirst μ := by
  ext a
  rw [finiteFirst_mass, finiteFirst_mass]
  simp only [finiteExtendRight, Fintype.sum_prod_type]
  simp_rw [← Finset.mul_sum, (κ _).total]
  simp

/-- The extended right marginal is the joint law of (V,W). -/
theorem finiteSecond_extendRight {α β γ : Type*} [Fintype α] [Fintype β] [Fintype γ]
    (μ : FiniteLaw (α × β)) (κ : β → FiniteLaw γ) :
    finiteSecond (finiteExtendRight μ κ) = finiteJoint (finiteSecond μ) κ := by
  ext z
  rw [finiteSecond_mass]
  simp only [finiteExtendRight, finiteJoint, finiteSecond_mass, ← Finset.sum_mul]

/-- KL chain rule when the added output kernel depends only on the second coordinate. -/
theorem finiteKLReal_extendRight {α β γ : Type*} [Fintype α] [Fintype β] [Fintype γ]
    (ν μ : FiniteLaw (α × β)) (τ κ : β → FiniteLaw γ)
    (hμ : ∀ z, 0 < μ.mass z) (hκ : ∀ b c, 0 < (κ b).mass c) :
    finiteKLReal (finiteExtendRight ν τ) (finiteExtendRight μ κ) = finiteKLReal ν μ +
      ∑ b, (finiteSecond ν).mass b * finiteKLReal (τ b) (κ b) := by
  simp only [finiteKLReal, finiteExtendRight, Fintype.sum_prod_type]
  simp_rw [finiteKL_atom_product _ _ (hμ _).ne' (hκ _ _).ne']
  simp_rw [Finset.sum_add_distrib, ← Finset.sum_mul, ← Finset.mul_sum, (τ _).total, one_mul]
  congr 1
  rw [Finset.sum_comm]
  simp_rw [← Finset.sum_mul, ← finiteSecond_mass]

/-- Entropy lifting is preserved when a stochastic output is appended on the right.
The conditional KL cost of the appended output is paid with coefficient at most one. -/
theorem entropyLifting_extendRight {α β γ : Type*} [Fintype α] [Fintype β] [Fintype γ]
    (μ : FiniteLaw (α × β)) (κ : β → FiniteLaw γ)
    (hμ : ∀ z, 0 < μ.mass z) (hκ : ∀ b c, 0 < (κ b).mass c)
    {a : ℝ} (ha : a ∈ Set.Icc (0 : ℝ) 1) (hlift : EntropyLifting μ a) :
    EntropyLifting (finiteExtendRight μ κ) a := by
  intro ν
  obtain ⟨σ, hσ, hcost⟩ := hlift (finiteFirst ν)
  refine ⟨finiteExtendRight σ (finiteConditionalLaw ν), ⟨?_, ?_⟩, ?_⟩
  · rw [finiteFirst_extendRight, finiteFirst_extendRight, hσ.1]
  · rw [finiteSecond_extendRight, hσ.2, finiteJoint_conditional]
  · rw [finiteKLReal_extendRight _ _ _ _ hμ hκ, hσ.2, finiteSecond_extendRight]
    have hc := finiteKLReal_joint (finiteFirst ν) (finiteSecond μ) (finiteConditionalLaw ν) κ
      (finiteSecond_pos μ hμ) hκ
    rw [finiteJoint_conditional] at hc
    rw [hc]
    have hn : 0 ≤ ∑ b, (finiteFirst ν).mass b * finiteKLReal (finiteConditionalLaw ν b) (κ b) :=
      Finset.sum_nonneg (fun b _ => mul_nonneg ((finiteFirst ν).nonneg b)
        (finiteKLReal_nonneg _ _ (fun c hc => ((hκ b c).ne' hc).elim)))
    nlinarith [mul_nonneg (sub_nonneg.mpr ha.2) hn]

/-- A surjective map of a positive reference law has a positive output law. -/
theorem finiteMap_pos {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw α) (hμ : ∀ a, 0 < μ.mass a) (f : α → β) (hf : Function.Surjective f)
    (b : β) : 0 < (finiteMap μ f).mass b := by
  classical
  obtain ⟨a, ha⟩ := hf b
  have h : μ.mass a ≤ (finiteMap μ f).mass b := by
    have h := Finset.single_le_sum
      (f := fun a => if f a = b then μ.mass a else 0)
      (fun a _ => by split_ifs; exact (hμ a).le; rfl) (Finset.mem_univ a)
    simpa [ha, finiteMap] using h
  exact (hμ a).trans_le h

/-- Entropy lifting holds at the reverse coefficient itself. -/
theorem entropyLifting_at_coefficient {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) (hμ : ∀ z, 0 < μ.mass z) :
    EntropyLifting μ (1-sDagger μ) := by
  rw [one_sub_sDagger]
  apply entropyLifting_of_reverseComplement μ hμ ENNReal.toReal_nonneg
  rw [ENNReal.ofReal_toReal (ne_top_of_le_ne_top (by simp) (reverseComplement_le_one μ))]

/-- Transfer of the lifting bound at the source coefficient implies coefficient contraction. -/
theorem sDagger_le_of_lifting {α β γ δ : Type*} [Fintype α] [Fintype β]
    [Fintype γ] [Fintype δ] (μ : FiniteLaw (α × β)) (ν : FiniteLaw (γ × δ))
    (hν : ∀ z, 0 < ν.mass z) (hlift : EntropyLifting ν (1-sDagger μ)) :
    sDagger ν ≤ sDagger μ := by
  have hm := sDagger_mem_Icc μ
  have ha : 1-sDagger μ ∈ Set.Icc (0 : ℝ) 1 := ⟨by linarith [hm.2], by linarith [hm.1]⟩
  have h := reverseComplement_ge_of_lifting ν hν ha hlift
  have hreal := ENNReal.toReal_mono
    (ne_top_of_le_ne_top (by simp) (reverseComplement_le_one ν)) h
  rw [ENNReal.toReal_ofReal ha.1] at hreal
  unfold sDagger
  unfold sDagger at hreal
  linarith

/-- Appending a conditionally independent output cannot increase the reverse coefficient. -/
theorem sDagger_extendRight_le {α β γ : Type*} [Fintype α] [Fintype β] [Fintype γ]
    (μ : FiniteLaw (α × β)) (κ : β → FiniteLaw γ)
    (hμ : ∀ z, 0 < μ.mass z) (hκ : ∀ b c, 0 < (κ b).mass c) :
    sDagger (finiteExtendRight μ κ) ≤ sDagger μ := by
  have hm := sDagger_mem_Icc μ
  have ha : 1-sDagger μ ∈ Set.Icc (0 : ℝ) 1 := ⟨by linarith [hm.2], by linarith [hm.1]⟩
  apply sDagger_le_of_lifting μ _ (fun z => mul_pos (hμ _) (hκ _ _))
  exact entropyLifting_extendRight μ κ hμ hκ ha (entropyLifting_at_coefficient μ hμ)

/-- Stochastic processing of V: keep U and output W from the conditional kernel. -/
def finiteRightChannel {α β γ : Type*} [Fintype α] [Fintype β] [Fintype γ]
    (μ : FiniteLaw (α × β)) (κ : β → FiniteLaw γ) : FiniteLaw (α × γ) :=
  finiteMap (finiteExtendRight μ κ) (fun z => (z.1,z.2.2))

/-- Stochastic data processing on the right, for positive reference tables and channels.
This includes the strictly positive biased perturbations used to handle c=d. -/
theorem sDagger_rightChannel_le {α β γ : Type*} [Fintype α] [Fintype β] [Fintype γ]
    (μ : FiniteLaw (α × β)) (κ : β → FiniteLaw γ)
    (hμ : ∀ z, 0 < μ.mass z) (hκ : ∀ b c, 0 < (κ b).mass c) :
    sDagger (finiteRightChannel μ κ) ≤ sDagger μ := by
  have hpos : ∀ z, 0 < (finiteExtendRight μ κ).mass z := fun z => mul_pos (hμ _) (hκ _ _)
  have hsurj : Function.Surjective (fun z : α × (β × γ) => (z.1,z.2.2)) := by
    obtain ⟨z⟩ := finiteLaw_nonempty μ
    intro ac
    exact ⟨(ac.1,z.2,ac.2), rfl⟩
  exact (sDagger_map_le (finiteExtendRight μ κ) hpos id Prod.snd
    (finiteMap_pos _ hpos _ hsurj)).trans (sDagger_extendRight_le μ κ hμ hκ)

/-- Bernoulli law, with `true` representing the atom +1. -/
def bernoulliLaw (p : ℝ) (hp : p ∈ Set.Icc (0 : ℝ) 1) : FiniteLaw Bool where
  mass b := if b then p else 1-p
  nonneg b := by cases b <;> simp; linarith [hp.2]; exact hp.1
  total := by simp

/-- The uniform law on a single sign. -/
def uniformBool : FiniteLaw Bool := bernoulliLaw (1/2) ⟨by norm_num, by norm_num⟩

/-- A strictly positive Bernoulli law parameterized by its log odds. -/
def sigmoidLaw (t : ℝ) : FiniteLaw Bool :=
  bernoulliLaw (Real.sigmoid t) ⟨(Real.sigmoid_pos _).le, (Real.sigmoid_lt_one _).le⟩

/-- Log odds of a Bernoulli probability. -/
def logOdds (p : ℝ) : ℝ := Real.log p - Real.log (1-p)

/-- The log odds of a sigmoid equal its real parameter. -/
theorem logOdds_sigmoid (t : ℝ) : logOdds (Real.sigmoid t) = t := by
  have hs := Real.sigmoid_pos t
  have hc : 0 < 1-Real.sigmoid t := sub_pos.mpr (Real.sigmoid_lt_one t)
  have he : Real.sigmoid t / (1-Real.sigmoid t) = Real.exp t := by
    rw [← Real.sigmoid_neg, ← Real.sigmoid_mul_rexp_neg,
      div_mul_eq_div_div, div_self hs.ne', one_div, ← Real.exp_neg, neg_neg]
  rw [logOdds, ← Real.log_div hs.ne' hc.ne', he, Real.log_exp]

/-- Every interior Bernoulli probability is recovered from its log odds. -/
theorem sigmoid_logOdds {p : ℝ} (hp : p ∈ Set.Ioo (0 : ℝ) 1) : Real.sigmoid (logOdds p) = p := by
  have h : p ∈ Set.range Real.sigmoid := by rw [Real.range_sigmoid]; exact hp
  obtain ⟨t, rfl⟩ := h
  rw [logOdds_sigmoid]

/-- Positivity of both atoms in a sigmoid-parametrized law. -/
theorem sigmoidLaw_pos (t : ℝ) (b : Bool) : 0 < (sigmoidLaw t).mass b := by
  cases b
  · exact sub_pos.mpr (Real.sigmoid_lt_one t)
  · exact Real.sigmoid_pos t

/-- Conditional exponential tilt of a binary symmetric reference channel.
At t=0 the conditional log odds are k and -k, and U is uniform. -/
def bscTilt (k t : ℝ) : FiniteLaw (Bool × Bool) :=
  finiteJoint uniformBool (fun u => sigmoidLaw (t + if u then k else -k))

/-- The second marginal probability of true in the tilted law. -/
def bscTiltMean (k t : ℝ) : ℝ := (Real.sigmoid (t+k) + Real.sigmoid (t-k))/2

/-- All four atoms of a finite binary tilt are positive. -/
theorem bscTilt_pos (k t : ℝ) (z : Bool × Bool) : 0 < (bscTilt k t).mass z := by
  apply mul_pos _ (sigmoidLaw_pos _ _)
  cases z.1 <;> norm_num [uniformBool, bernoulliLaw]

/-- Conditional tilting leaves the U marginal uniform. -/
theorem bscTilt_first (k t : ℝ) : finiteFirst (bscTilt k t) = uniformBool := finiteFirst_joint _ _

/-- The tilted marginal's true probability is the average of its two conditional probabilities. -/
theorem bscTilt_second_true (k t : ℝ) :
    (finiteSecond (bscTilt k t)).mass true = bscTiltMean k t := by
  rw [finiteSecond_mass]
  simp [bscTilt, finiteJoint, uniformBool, bernoulliLaw, sigmoidLaw, bscTiltMean, sub_eq_add_neg]
  ring

/-- The mean of two interior Bernoulli probabilities is interior. -/
theorem bscTiltMean_mem (k t : ℝ) : bscTiltMean k t ∈ Set.Ioo (0 : ℝ) 1 := by
  unfold bscTiltMean
  constructor <;> linarith [Real.sigmoid_pos (t+k), Real.sigmoid_pos (t-k),
    Real.sigmoid_lt_one (t+k), Real.sigmoid_lt_one (t-k)]

/-- The untilted binary-symmetric reference has uniform V marginal. -/
theorem bscTiltMean_zero (k : ℝ) : bscTiltMean k 0 = 1/2 := by
  simp [bscTiltMean, Real.sigmoid_neg]

/-- The tilted marginal is a continuous function of the common log-odds shift. -/
theorem continuous_bscTiltMean (k : ℝ) : Continuous (bscTiltMean k) := by
  unfold bscTiltMean
  fun_prop

/-- Every interior V marginal is attained by a common conditional log-odds shift. -/
theorem bscTiltMean_surjective (k : ℝ) {p : ℝ} (hp : p ∈ Set.Ioo (0 : ℝ) 1) :
    ∃ t, bscTiltMean k t = p := by
  let l := logOdds p - |k|
  let u := logOdds p + |k|
  have hlu : l ≤ u := by dsimp [l,u]; linarith [abs_nonneg k]
  have hl : bscTiltMean k l ≤ p := by
    have h₁ : l+k ≤ logOdds p := by dsimp [l]; linarith [le_abs_self k]
    have h₂ : l-k ≤ logOdds p := by dsimp [l]; linarith [neg_le_abs k]
    have h₃ := Real.sigmoid_le h₁
    have h₄ := Real.sigmoid_le h₂
    rw [sigmoid_logOdds hp] at h₃ h₄
    unfold bscTiltMean
    linarith
  have hu : p ≤ bscTiltMean k u := by
    have h₁ : logOdds p ≤ u+k := by dsimp [u]; linarith [neg_le_abs k]
    have h₂ : logOdds p ≤ u-k := by dsimp [u]; linarith [le_abs_self k]
    have h₃ := Real.sigmoid_le h₁
    have h₄ := Real.sigmoid_le h₂
    rw [sigmoid_logOdds hp] at h₃ h₄
    unfold bscTiltMean
    linarith
  obtain ⟨t, _, ht⟩ := intermediate_value_Icc hlu (continuous_bscTiltMean k).continuousOn ⟨hl,hu⟩
  exact ⟨t, ht⟩

/-- Atomwise change of KL reference, including a zero target mass. -/
theorem finiteKL_atom_change_reference (x : ℝ) {y z : ℝ} (hy : y ≠ 0) (hz : z ≠ 0) :
    x * Real.log (x/y) = x * Real.log (x/z) + x * Real.log (z/y) := by
  by_cases hx : x = 0
  · simp [hx]
  rw [Real.log_div hx hy, Real.log_div hx hz, Real.log_div hz hy]
  ring

/-- Expected sums of separate coordinate functions depend only on the two marginals. -/
theorem finiteExpectation_separable {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw (α × β)) (f : α → ℝ) (g : β → ℝ) :
    finiteExpectation μ (fun z => f z.1 + g z.2) =
      finiteExpectation (finiteFirst μ) f + finiteExpectation (finiteSecond μ) g := by
  rw [finiteFirst, finiteSecond, finiteExpectation_map, finiteExpectation_map]
  simp [finiteExpectation, mul_add, Finset.sum_add_distrib]

/-- Entropy Pythagorean identity when the optimal log-density ratio is a sum of
one potential for each constrained marginal. -/
theorem finiteKLReal_pythagoras {α β : Type*} [Fintype α] [Fintype β]
    (κ ν μ : FiniteLaw (α × β)) (hν : ∀ z, 0 < ν.mass z) (hμ : ∀ z, 0 < μ.mass z)
    (f : α → ℝ) (g : β → ℝ)
    (hpot : ∀ z, Real.log (ν.mass z / μ.mass z) = f z.1 + g z.2)
    (hfirst : finiteFirst κ = finiteFirst ν) (hsecond : finiteSecond κ = finiteSecond ν) :
    finiteKLReal κ μ = finiteKLReal κ ν + finiteKLReal ν μ := by
  have hchange : finiteKLReal κ μ = finiteKLReal κ ν +
      finiteExpectation κ (fun z => Real.log (ν.mass z / μ.mass z)) := by
    unfold finiteKLReal finiteExpectation
    rw [← Finset.sum_add_distrib]
    apply Finset.sum_congr rfl
    intro z _
    exact finiteKL_atom_change_reference _ (hμ z).ne' (hν z).ne'
  rw [hchange]
  congr 1
  change finiteExpectation κ (fun z => Real.log (ν.mass z / μ.mass z)) =
    finiteExpectation ν (fun z => Real.log (ν.mass z / μ.mass z))
  simp_rw [hpot]
  rw [finiteExpectation_separable, finiteExpectation_separable, hfirst, hsecond]

/-- The Bernoulli conditional tilt has the required common log-odds multiplier. -/
theorem sigmoidLaw_logRatio (k t : ℝ) (b : Bool) :
    Real.log ((sigmoidLaw (t+k)).mass b / (sigmoidLaw k).mass b) =
      Real.log (1-Real.sigmoid (t+k)) - Real.log (1-Real.sigmoid k) +
        (if b then t else 0) := by
  have ht := logOdds_sigmoid (t+k)
  have hk := logOdds_sigmoid k
  unfold logOdds at ht hk
  cases b
  · change Real.log ((1-Real.sigmoid (t+k))/(1-Real.sigmoid k)) = _
    rw [Real.log_div (sub_pos.mpr (Real.sigmoid_lt_one _)).ne'
      (sub_pos.mpr (Real.sigmoid_lt_one _)).ne']
    simp
  · change Real.log (Real.sigmoid (t+k)/Real.sigmoid k) = _
    rw [Real.log_div (Real.sigmoid_pos _).ne' (Real.sigmoid_pos _).ne']
    dsimp
    linarith

/-- The tilted joint/reference log-density ratio separates into marginal potentials. -/
theorem bscTilt_logRatio (k t : ℝ) (z : Bool × Bool) :
    Real.log ((bscTilt k t).mass z / (bscTilt k 0).mass z) =
      (Real.log (1-Real.sigmoid (t + if z.1 then k else -k)) -
        Real.log (1-Real.sigmoid (if z.1 then k else -k))) +
          (if z.2 then t else 0) := by
  have huni : uniformBool.mass z.1 ≠ 0 := by cases z.1 <;> norm_num [uniformBool, bernoulliLaw]
  change Real.log ((uniformBool.mass z.1 * (sigmoidLaw _).mass z.2) /
    (uniformBool.mass z.1 * (sigmoidLaw _).mass z.2)) = _
  rw [mul_div_mul_left _ _ huni]
  simp only [zero_add]
  exact sigmoidLaw_logRatio _ _ _

/-- A common conditional log-odds tilt is the global entropy minimizer, including
all boundary-valued competitors satisfying its two marginal constraints. -/
theorem bscTilt_minimizes (k t : ℝ) (κ : FiniteLaw (Bool × Bool))
    (hκ : finiteTransportFeasible (bscTilt k 0) κ (finiteSecond (bscTilt k t))) :
    finiteKLReal (bscTilt k t) (bscTilt k 0) ≤ finiteKLReal κ (bscTilt k 0) := by
  have hfirst : finiteFirst κ = finiteFirst (bscTilt k t) := by
    rw [hκ.1, bscTilt_first, bscTilt_first]
  have he := finiteKLReal_pythagoras κ (bscTilt k t) (bscTilt k 0)
    (bscTilt_pos k t) (bscTilt_pos k 0)
    (fun u => Real.log (1-Real.sigmoid (t + if u then k else -k)) -
      Real.log (1-Real.sigmoid (if u then k else -k)))
    (fun v => if v then t else 0) (bscTilt_logRatio k t) hfirst hκ.2
  have hn := finiteKLReal_nonneg κ (bscTilt k t) (fun z hz => ((bscTilt_pos k t z).ne' hz).elim)
  linarith

/-- A law on a binary alphabet is determined by the probability of true. -/
theorem finiteLaw_bool_ext (μ ν : FiniteLaw Bool) (h : μ.mass true = ν.mass true) : μ = ν := by
  ext b
  cases b
  · have hμ := μ.total
    have hν := ν.total
    simp only [Fintype.sum_bool] at hμ hν
    linarith
  · exact h

/-- Every interior target marginal admits an entropy-minimizing common tilt. -/
theorem bscTilt_optimizer_exists (k : ℝ) (ν : FiniteLaw Bool)
    (hν : ν.mass true ∈ Set.Ioo (0 : ℝ) 1) :
    ∃ t, finiteTransportFeasible (bscTilt k 0) (bscTilt k t) ν ∧
      ∀ κ, finiteTransportFeasible (bscTilt k 0) κ ν →
        finiteKLReal (bscTilt k t) (bscTilt k 0) ≤ finiteKLReal κ (bscTilt k 0) := by
  obtain ⟨t, ht⟩ := bscTiltMean_surjective k hν
  have hm : finiteSecond (bscTilt k t) = ν :=
    finiteLaw_bool_ext _ _ ((bscTilt_second_true k t).trans ht)
  refine ⟨t, ⟨by rw [bscTilt_first, bscTilt_first], hm⟩, ?_⟩
  intro κ hκ
  apply bscTilt_minimizes k t κ
  rwa [hm]

/-- Correlation of the symmetric binary reference with log-odds parameter k. -/
def bscCorrelation (k : ℝ) : ℝ := 2 * Real.sigmoid k - 1

/-- The candidate entropy-lifting factor of the symmetric binary channel. -/
def bscFactor (k : ℝ) : ℝ := 1 - bscCorrelation k ^ 2

/-- The lifting factor is positive and at most one for finite log odds. -/
theorem bscFactor_mem (k : ℝ) : bscFactor k ∈ Set.Ioc (0 : ℝ) 1 := by
  have hp := Real.sigmoid_pos k
  have hq := Real.sigmoid_lt_one k
  unfold bscFactor bscCorrelation
  constructor
  · nlinarith [mul_pos hp (sub_pos.mpr hq)]
  · nlinarith [sq_nonneg (2 * Real.sigmoid k - 1)]

/-- Average conditional variance in the binary tilt. -/
def bscTiltVariance (k t : ℝ) : ℝ :=
  (Real.sigmoid (t+k) * (1-Real.sigmoid (t+k)) +
    Real.sigmoid (t-k) * (1-Real.sigmoid (t-k)))/2

/-- The derivative of the tilted mean is its average conditional variance. -/
theorem hasDerivAt_bscTiltMean (k t : ℝ) :
    HasDerivAt (bscTiltMean k) (bscTiltVariance k t) t := by
  have h₁ := (Real.hasDerivAt_sigmoid (t+k)).comp t ((hasDerivAt_id t).add_const k)
  have h₂ := (Real.hasDerivAt_sigmoid (t-k)).comp t ((hasDerivAt_id t).sub_const k)
  convert! (h₁.add h₂).div_const 2 using 1 <;> simp [bscTiltMean, bscTiltVariance]

/-- Positive conditional variance for every finite tilt. -/
theorem bscTiltVariance_pos (k t : ℝ) : 0 < bscTiltVariance k t := by
  unfold bscTiltVariance
  exact div_pos (add_pos
    (mul_pos (Real.sigmoid_pos _) (sub_pos.mpr (Real.sigmoid_lt_one _)))
    (mul_pos (Real.sigmoid_pos _) (sub_pos.mpr (Real.sigmoid_lt_one _)))) (by norm_num)

/-- Equivalent positive-exponential expression for the sigmoid. -/
theorem sigmoid_exp_fraction (t : ℝ) : Real.sigmoid t = Real.exp t / (1+Real.exp t) := by
  rw [Real.sigmoid_def, Real.exp_neg]
  field_simp
  <;> ring

/-- Exact rational identity proving the binary-channel curvature bound.
Here a=exp(k) and z=exp(t); every factor on the right is nonnegative. -/
theorem bsc_rational_curvature (a z : ℝ) (ha : 0 < a) (hz : 0 < z) :
    let x := a*z/(1+a*z)
    let y := z/(a+z)
    (x*(1-x)+y*(1-y))/2 -
      (1-((a-1)/(a+1))^2) * ((x+y)/2) * (1-(x+y)/2) =
    a*z*(a-1)^2*(a^2+1)*(z-1)^2 /
      (2*(a+1)^2*(a+z)^2*(a*z+1)^2) := by
  have h₁ : a+1 ≠ 0 := by positivity
  have h₂ : a+z ≠ 0 := by positivity
  have h₃ : a*z+1 ≠ 0 := by positivity
  have h₄ : 1+a*z ≠ 0 := by positivity
  dsimp
  field_simp
  <;> ring

/-- Curvature bound for the symmetric channel: conditional variance is at least
`(1-rho²)` times marginal variance, uniformly over every common log-odds tilt. -/
theorem bscTiltVariance_ge (k t : ℝ) :
    bscFactor k * bscTiltMean k t * (1-bscTiltMean k t) ≤ bscTiltVariance k t := by
  let a := Real.exp k
  let z := Real.exp t
  have ha : 0 < a := Real.exp_pos k
  have hz : 0 < z := Real.exp_pos t
  have hx : Real.sigmoid (t+k) = a*z/(1+a*z) := by
    rw [sigmoid_exp_fraction, Real.exp_add]
    dsimp [a,z]
    ring
  have hy : Real.sigmoid (t-k) = z/(a+z) := by
    rw [sigmoid_exp_fraction, Real.exp_sub]
    dsimp [a,z]
    field_simp
  have hr : bscCorrelation k = (a-1)/(a+1) := by
    rw [bscCorrelation, sigmoid_exp_fraction]
    dsimp [a]
    field_simp
    <;> ring
  have he := bsc_rational_curvature a z ha hz
  have hn : 0 ≤ a*z*(a-1)^2*(a^2+1)*(z-1)^2 /
      (2*(a+1)^2*(a+z)^2*(a*z+1)^2) := by positivity
  unfold bscFactor bscTiltMean bscTiltVariance
  rw [hx, hy, hr]
  dsimp at he
  linarith

/-- Derivative of Bernoulli log odds on the open interval. -/
theorem hasDerivAt_logOdds {p : ℝ} (hp : p ∈ Set.Ioo (0 : ℝ) 1) :
    HasDerivAt logOdds (1 / (p*(1-p))) p := by
  have h₁ := Real.hasDerivAt_log hp.1.ne'
  have h₂ := ((hasDerivAt_id p).const_sub 1).log (sub_pos.mpr hp.2).ne'
  convert! h₁.sub h₂ using 1
  dsimp
  field_simp [hp.1.ne', (sub_pos.mpr hp.2).ne']
  <;> ring

/-- Nonnegative derivative of the adjusted marginal log odds. -/
theorem bsc_adjusted_logOdds_deriv (k t : ℝ) :
    HasDerivAt (fun t => logOdds (bscTiltMean k t) - bscFactor k * t)
      ((bscTiltVariance k t - bscFactor k * bscTiltMean k t * (1-bscTiltMean k t)) /
        (bscTiltMean k t * (1-bscTiltMean k t))) t := by
  have hm := bscTiltMean_mem k t
  have h := ((hasDerivAt_logOdds hm).comp t (hasDerivAt_bscTiltMean k t)).sub
    ((hasDerivAt_id t).const_mul (bscFactor k))
  convert! h using 1
  field_simp [hm.1.ne', (sub_pos.mpr hm.2).ne']
  <;> ring

/-- Marginal log odds grow at least at rate `1-rho²` under conditional exponential tilt. -/
theorem bsc_adjusted_logOdds_monotone (k : ℝ) :
    Monotone (fun t => logOdds (bscTiltMean k t) - bscFactor k * t) := by
  apply monotone_of_hasDerivAt_nonneg (bsc_adjusted_logOdds_deriv k)
  intro t
  exact div_nonneg (sub_nonneg.mpr (bscTiltVariance_ge k t))
    (mul_nonneg (bscTiltMean_mem k t).1.le (sub_pos.mpr (bscTiltMean_mem k t).2).le)

/-- The adjusted marginal log odds vanish at the symmetric reference. -/
theorem bsc_adjusted_logOdds_zero (k : ℝ) :
    logOdds (bscTiltMean k 0) - bscFactor k * 0 = 0 := by
  rw [bscTiltMean_zero]
  norm_num [logOdds]

/-- Binary KL in real coordinates with an interior reference probability. -/
def finiteBinaryKL (x q : ℝ) : ℝ :=
  x * Real.log (x/q) + (1-x) * Real.log ((1-x)/(1-q))

/-- The scalar binary formula agrees with finite-law KL. -/
theorem finiteKLReal_bernoulli {x q : ℝ}
    (hx : x ∈ Set.Icc (0 : ℝ) 1) (hq : q ∈ Set.Icc (0 : ℝ) 1) :
    finiteKLReal (bernoulliLaw x hx) (bernoulliLaw q hq) = finiteBinaryKL x q := by
  simp [finiteKLReal, bernoulliLaw, finiteBinaryKL]

/-- Binary KL cross-entropy expansion on the full target interval. -/
theorem finiteBinaryKL_expand (x : ℝ) {q : ℝ} (hq : q ∈ Set.Ioo (0 : ℝ) 1) :
    finiteBinaryKL x q = x*Real.log x+(1-x)*Real.log (1-x) -
      x*Real.log q-(1-x)*Real.log (1-q) := by
  rw [finiteBinaryKL, finiteKL_atom_expand _ hq.1.ne',
    finiteKL_atom_expand _ (sub_pos.mpr hq.2).ne']
  ring

/-- Binary KL is continuous up to the target boundary for interior reference. -/
theorem continuous_finiteBinaryKL {q : ℝ} (hq : q ∈ Set.Ioo (0 : ℝ) 1) :
    Continuous (fun x => finiteBinaryKL x q) := by
  simp_rw [finiteBinaryKL_expand _ hq]
  exact ((Real.continuous_mul_log.add
    (Real.continuous_mul_log.comp (continuous_const.sub continuous_id))).sub
    (continuous_id.mul_const _)).sub ((continuous_const.sub continuous_id).mul_const _)

/-- Derivative of binary KL in its first probability. -/
theorem hasDerivAt_finiteBinaryKL {x q : ℝ}
    (hx : x ∈ Set.Ioo (0 : ℝ) 1) (hq : q ∈ Set.Ioo (0 : ℝ) 1) :
    HasDerivAt (fun x => finiteBinaryKL x q) (logOdds x - logOdds q) x := by
  have he : (fun x => finiteBinaryKL x q) = (fun x => x*Real.log x+(1-x)*Real.log (1-x) -
      x*Real.log q-(1-x)*Real.log (1-q)) := funext (fun x => finiteBinaryKL_expand x hq)
  rw [he]
  have h := (((Real.hasDerivAt_mul_log hx.1.ne').add
    ((Real.hasDerivAt_mul_log (sub_pos.mpr hx.2).ne').comp x ((hasDerivAt_id x).const_sub 1))).sub
    ((hasDerivAt_id x).mul_const (Real.log q))).sub
    (((hasDerivAt_id x).const_sub 1).mul_const (Real.log (1-q)))
  convert! h using 1
  unfold logOdds
  ring

/-- Binary KL is zero at an unchanged probability. -/
theorem finiteBinaryKL_self (x : ℝ) : finiteBinaryKL x x = 0 := by simp [finiteBinaryKL]

/-- Entropy cost of the common conditional tilt of a binary symmetric reference. -/
def bscTiltCost (k t : ℝ) : ℝ :=
  (finiteBinaryKL (Real.sigmoid (t+k)) (Real.sigmoid k) +
    finiteBinaryKL (Real.sigmoid (t-k)) (Real.sigmoid (-k)))/2

/-- The scalar cost formula is the KL cost of the actual joint probability law. -/
theorem bscTiltCost_eq_KL (k t : ℝ) :
    bscTiltCost k t = finiteKLReal (bscTilt k t) (bscTilt k 0) := by
  have hu : ∀ b, 0 < uniformBool.mass b := by intro b; cases b <;> norm_num [uniformBool,bernoulliLaw]
  have he := finiteKLReal_joint uniformBool uniformBool
    (fun u => sigmoidLaw (t + if u then k else -k))
    (fun u => sigmoidLaw (0 + if u then k else -k)) hu
    (fun u b => sigmoidLaw_pos _ _)
  change finiteKLReal (bscTilt k t) (bscTilt k 0) = _ at he
  have hb (x y : ℝ) : finiteKLReal (sigmoidLaw x) (sigmoidLaw y) =
      finiteBinaryKL (Real.sigmoid x) (Real.sigmoid y) :=
    finiteKLReal_bernoulli _ _
  simp_rw [hb] at he
  rw [he, finiteKLReal_self, zero_add]
  simp only [Fintype.sum_bool, uniformBool, bernoulliLaw]
  simp only [Bool.false_eq_true, ite_false, ite_true, zero_add]
  unfold bscTiltCost
  simp only [sub_eq_add_neg]
  ring

/-- The derivative of the tilted entropy cost is shift times conditional variance. -/
theorem hasDerivAt_bscTiltCost (k t : ℝ) :
    HasDerivAt (bscTiltCost k) (t * bscTiltVariance k t) t := by
  have h₁ := ((hasDerivAt_finiteBinaryKL
    ⟨Real.sigmoid_pos (t+k), Real.sigmoid_lt_one (t+k)⟩
    ⟨Real.sigmoid_pos k, Real.sigmoid_lt_one k⟩).comp t
    ((Real.hasDerivAt_sigmoid (t+k)).comp t ((hasDerivAt_id t).add_const k)))
  have h₂ := ((hasDerivAt_finiteBinaryKL
    ⟨Real.sigmoid_pos (t-k), Real.sigmoid_lt_one (t-k)⟩
    ⟨Real.sigmoid_pos (-k), Real.sigmoid_lt_one (-k)⟩).comp t
    ((Real.hasDerivAt_sigmoid (t-k)).comp t ((hasDerivAt_id t).sub_const k)))
  have he := (h₁.add h₂).div_const 2
  simp only [logOdds_sigmoid] at he
  convert! he using 1
  unfold bscTiltVariance
  ring

/-- Difference between marginal entropy and the scaled conditional entropy cost. -/
def bscEntropyMargin (k t : ℝ) : ℝ :=
  finiteBinaryKL (bscTiltMean k t) (1/2) - bscFactor k * bscTiltCost k t

/-- Exact derivative of the entropy comparison margin. -/
theorem hasDerivAt_bscEntropyMargin (k t : ℝ) :
    HasDerivAt (bscEntropyMargin k)
      ((logOdds (bscTiltMean k t) - bscFactor k*t) * bscTiltVariance k t) t := by
  have h := ((hasDerivAt_finiteBinaryKL (q := (1/2 : ℝ)) (bscTiltMean_mem k t)
    (by constructor <;> norm_num)).comp t (hasDerivAt_bscTiltMean k t)).sub
    ((hasDerivAt_bscTiltCost k t).const_mul (bscFactor k))
  convert! h using 1
  norm_num [logOdds]
  ring

/-- The entropy comparison margin vanishes at the symmetric reference. -/
theorem bscEntropyMargin_zero (k : ℝ) : bscEntropyMargin k 0 = 0 := by
  unfold bscEntropyMargin
  rw [bscTiltMean_zero, finiteBinaryKL_self]
  simp [bscTiltCost, finiteBinaryKL_self]

/-- The binary symmetric entropy-lifting bound holds at every finite conditional tilt. -/
theorem bscTiltCost_bound (k t : ℝ) :
    bscFactor k * bscTiltCost k t ≤ finiteBinaryKL (bscTiltMean k t) (1/2) := by
  have hc : Continuous (bscEntropyMargin k) :=
    continuous_iff_continuousAt.mpr (fun t => (hasDerivAt_bscEntropyMargin k t).continuousAt)
  have hm := bsc_adjusted_logOdds_monotone k
  have hzero := bsc_adjusted_logOdds_zero k
  by_cases ht : 0 ≤ t
  · have hmono : MonotoneOn (bscEntropyMargin k) (Set.Ici 0) :=
      monotoneOn_of_hasDerivWithinAt_nonneg (convex_Ici 0) hc.continuousOn
        (fun x _ => (hasDerivAt_bscEntropyMargin k x).hasDerivWithinAt)
        (fun x hx => mul_nonneg (by have h := hm (Set.mem_Ici.mp (interior_subset hx)); linarith)
          (bscTiltVariance_pos k x).le)
    have h := hmono (by simp) ht ht
    rw [bscEntropyMargin_zero] at h
    exact sub_nonneg.mp h
  · have ht' : t ≤ 0 := le_of_not_ge ht
    have hanti : AntitoneOn (bscEntropyMargin k) (Set.Iic 0) :=
      antitoneOn_of_hasDerivWithinAt_nonpos (convex_Iic 0) hc.continuousOn
        (fun x _ => (hasDerivAt_bscEntropyMargin k x).hasDerivWithinAt)
        (fun x hx => mul_nonpos_of_nonpos_of_nonneg
          (by have h := hm (Set.mem_Iic.mp (interior_subset hx)); linarith)
          (bscTiltVariance_pos k x).le)
    have h := hanti ht' (by simp) ht'
    rw [bscEntropyMargin_zero] at h
    exact sub_nonneg.mp h

/-- Limit form of the binary entropy bound when both conditional probabilities
approach the same endpoint. No division by a vanishing probability is introduced. -/
theorem bscTiltCost_bound_of_limits (k : ℝ) {l : Filter ℝ} [Filter.NeBot l] {p : ℝ}
    (h₁ : Filter.Tendsto (fun t => Real.sigmoid (t+k)) l (nhds p))
    (h₂ : Filter.Tendsto (fun t => Real.sigmoid (t-k)) l (nhds p)) :
    bscFactor k * ((finiteBinaryKL p (Real.sigmoid k) + finiteBinaryKL p (Real.sigmoid (-k)))/2) ≤
      finiteBinaryKL p (1/2) := by
  have hcost := (((continuous_finiteBinaryKL ⟨Real.sigmoid_pos k, Real.sigmoid_lt_one k⟩).tendsto p).comp h₁).add
    (((continuous_finiteBinaryKL ⟨Real.sigmoid_pos (-k), Real.sigmoid_lt_one (-k)⟩).tendsto p).comp h₂)
  have hleft := (hcost.div_const 2).const_mul (bscFactor k)
  have hm : Filter.Tendsto (bscTiltMean k) l (nhds p) := by
    convert! (h₁.add h₂).div_const 2 using 1 <;> simp [bscTiltMean]
  have hright := ((continuous_finiteBinaryKL (q := (1/2 : ℝ))
    (by constructor <;> norm_num)).tendsto p).comp hm
  exact le_of_tendsto_of_tendsto' hleft hright (bscTiltCost_bound k)

/-- The entropy-lifting bound at the all-false target marginal. -/
theorem bscEndpointCost_zero (k : ℝ) :
    bscFactor k * ((finiteBinaryKL 0 (Real.sigmoid k) + finiteBinaryKL 0 (Real.sigmoid (-k)))/2) ≤
      finiteBinaryKL 0 (1/2) := by
  apply bscTiltCost_bound_of_limits k (l := Filter.atBot)
  · exact Real.tendsto_sigmoid_atBot.comp
      (Filter.tendsto_atBot_add_const_right _ k Filter.tendsto_id)
  · simpa only [Function.comp_def, id_eq, sub_eq_add_neg] using Real.tendsto_sigmoid_atBot.comp
      (Filter.tendsto_atBot_add_const_right _ (-k) Filter.tendsto_id)

/-- The entropy-lifting bound at the all-true target marginal. -/
theorem bscEndpointCost_one (k : ℝ) :
    bscFactor k * ((finiteBinaryKL 1 (Real.sigmoid k) + finiteBinaryKL 1 (Real.sigmoid (-k)))/2) ≤
      finiteBinaryKL 1 (1/2) := by
  apply bscTiltCost_bound_of_limits k (l := Filter.atTop)
  · exact Real.tendsto_sigmoid_atTop.comp
      (Filter.tendsto_atTop_add_const_right _ k Filter.tendsto_id)
  · simpa only [Function.comp_def, id_eq, sub_eq_add_neg] using Real.tendsto_sigmoid_atTop.comp
      (Filter.tendsto_atTop_add_const_right _ (-k) Filter.tendsto_id)

/-- Any binary law is the Bernoulli law of its true probability. -/
theorem finiteLaw_bool_eq_bernoulli (ν : FiniteLaw Bool) :
    ν = bernoulliLaw (ν.mass true) ⟨ν.nonneg true, finiteLaw_mass_le_one ν true⟩ :=
  finiteLaw_bool_ext _ _ rfl

/-- The symmetric reference's second marginal is uniform. -/
theorem bscTilt_second_zero (k : ℝ) : finiteSecond (bscTilt k 0) = uniformBool := by
  apply finiteLaw_bool_ext
  rw [bscTilt_second_true, bscTiltMean_zero]
  rfl

/-- The second marginal of an independent joint law is its second factor. -/
theorem finiteSecond_joint_const {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw α) (ν : FiniteLaw β) : finiteSecond (finiteJoint μ (fun _ => ν)) = ν := by
  ext b
  rw [finiteSecond_mass]
  change (∑ a, μ.mass a * ν.mass b) = ν.mass b
  rw [← Finset.sum_mul, μ.total, one_mul]

/-- KL cost of forcing the same binary target law in both rows of the symmetric reference. -/
theorem bsc_constant_kernel_cost (k : ℝ) (ν : FiniteLaw Bool) :
    finiteKLReal (finiteJoint uniformBool (fun _ => ν)) (bscTilt k 0) =
      (finiteBinaryKL (ν.mass true) (Real.sigmoid k) +
        finiteBinaryKL (ν.mass true) (Real.sigmoid (-k)))/2 := by
  have hu : ∀ b, 0 < uniformBool.mass b := by intro b; cases b <;> norm_num [uniformBool,bernoulliLaw]
  have he := finiteKLReal_joint uniformBool uniformBool (fun _ => ν)
    (fun u => sigmoidLaw (0 + if u then k else -k)) hu (fun u b => sigmoidLaw_pos _ _)
  change finiteKLReal _ (bscTilt k 0) = _ at he
  rw [he, finiteKLReal_self, zero_add]
  have hb (t : ℝ) : finiteKLReal ν (sigmoidLaw t) = finiteBinaryKL (ν.mass true) (Real.sigmoid t) := by
    nth_rw 1 [finiteLaw_bool_eq_bernoulli ν]
    exact finiteKLReal_bernoulli _ _
  simp_rw [hb]
  simp [Fintype.sum_bool, uniformBool, bernoulliLaw]
  ring

/-- Entropy lifting for the binary symmetric channel, including both endpoint target laws.
The coefficient is exactly the candidate 1-rho²; sharpness is proved separately. -/
theorem entropyLifting_bscTilt (k : ℝ) : EntropyLifting (bscTilt k 0) (bscFactor k) := by
  intro ν
  have hν : ν.mass true ∈ Set.Icc (0 : ℝ) 1 := ⟨ν.nonneg true, finiteLaw_mass_le_one ν true⟩
  have hr : finiteKLReal ν (finiteSecond (bscTilt k 0)) = finiteBinaryKL (ν.mass true) (1/2) := by
    rw [bscTilt_second_zero]
    nth_rw 1 [finiteLaw_bool_eq_bernoulli ν]
    exact finiteKLReal_bernoulli _ _
  by_cases h0 : ν.mass true = 0
  · refine ⟨finiteJoint uniformBool (fun _ => ν), ⟨?_, finiteSecond_joint_const _ _⟩, ?_⟩
    · rw [finiteFirst_joint, bscTilt_first]
    · rw [bsc_constant_kernel_cost, hr, h0]
      exact bscEndpointCost_zero k
  by_cases h1 : ν.mass true = 1
  · refine ⟨finiteJoint uniformBool (fun _ => ν), ⟨?_, finiteSecond_joint_const _ _⟩, ?_⟩
    · rw [finiteFirst_joint, bscTilt_first]
    · rw [bsc_constant_kernel_cost, hr, h1]
      exact bscEndpointCost_one k
  have hi : ν.mass true ∈ Set.Ioo (0 : ℝ) 1 :=
    ⟨lt_of_le_of_ne hν.1 (Ne.symm h0), lt_of_le_of_ne hν.2 h1⟩
  obtain ⟨t, ht⟩ := bscTiltMean_surjective k hi
  have hm : finiteSecond (bscTilt k t) = ν :=
    finiteLaw_bool_ext _ _ ((bscTilt_second_true k t).trans ht)
  refine ⟨bscTilt k t, ⟨by rw [bscTilt_first,bscTilt_first], hm⟩, ?_⟩
  rw [← bscTiltCost_eq_KL, hr, ← ht]
  exact bscTiltCost_bound k t

/-- The doubly symmetric binary law with correlation rho. -/
def binarySymmetricLaw (ρ : ℝ) (hρ : ρ ∈ Set.Icc (-1 : ℝ) 1) : FiniteLaw (Bool × Bool) where
  mass z := if z.1 = z.2 then (1+ρ)/4 else (1-ρ)/4
  nonneg z := by split_ifs <;> linarith [hρ.1,hρ.2]
  total := by simp [Fintype.sum_prod_type]; ring

/-- A nondegenerate binary symmetric law has all four atoms positive. -/
theorem binarySymmetricLaw_pos {ρ : ℝ} (hρ : ρ ∈ Set.Ioo (-1 : ℝ) 1) (z : Bool × Bool) :
    0 < (binarySymmetricLaw ρ ⟨hρ.1.le,hρ.2.le⟩).mass z := by
  dsimp [binarySymmetricLaw]
  split_ifs <;> linarith [hρ.1,hρ.2]

/-- Log-odds parameter of the channel with correlation rho. -/
def bscLogOdds (ρ : ℝ) : ℝ := logOdds ((1+ρ)/2)

/-- The logistic parameterization preserves exactly the specified channel correlation. -/
theorem bscCorrelation_logOdds {ρ : ℝ} (hρ : ρ ∈ Set.Ioo (-1 : ℝ) 1) :
    bscCorrelation (bscLogOdds ρ) = ρ := by
  have hp : (1+ρ)/2 ∈ Set.Ioo (0 : ℝ) 1 := ⟨by linarith [hρ.1],by linarith [hρ.2]⟩
  rw [bscCorrelation,bscLogOdds,sigmoid_logOdds hp]
  ring

/-- The untilted reference is exactly the binary symmetric probability table. -/
theorem bscTilt_eq_binarySymmetric {ρ : ℝ} (hρ : ρ ∈ Set.Ioo (-1 : ℝ) 1) :
    bscTilt (bscLogOdds ρ) 0 = binarySymmetricLaw ρ ⟨hρ.1.le,hρ.2.le⟩ := by
  have hp : (1+ρ)/2 ∈ Set.Ioo (0 : ℝ) 1 := ⟨by linarith [hρ.1],by linarith [hρ.2]⟩
  ext z
  obtain ⟨u,v⟩ := z
  cases u <;> cases v <;>
    simp [bscTilt, finiteJoint, uniformBool, sigmoidLaw, bernoulliLaw, binarySymmetricLaw,
      Real.sigmoid_neg, bscLogOdds, sigmoid_logOdds hp] <;> ring

/-- Entropy lifting with factor 1-rho² for every nondegenerate binary symmetric channel. -/
theorem entropyLifting_binarySymmetric {ρ : ℝ} (hρ : ρ ∈ Set.Ioo (-1 : ℝ) 1) :
    EntropyLifting (binarySymmetricLaw ρ ⟨hρ.1.le,hρ.2.le⟩) (1-ρ^2) := by
  have h := entropyLifting_bscTilt (bscLogOdds ρ)
  rwa [bscTilt_eq_binarySymmetric hρ, bscFactor, bscCorrelation_logOdds hρ] at h

/-- Reindexing by a bijection simply relabels atom masses. -/
theorem finiteMap_equiv_mass {α β : Type*} [Fintype α] [Fintype β]
    (μ : FiniteLaw α) (e : α ≃ β) (b : β) : (finiteMap μ e).mass b = μ.mass (e.symm b) := by
  classical
  simp [finiteMap, e.apply_eq_iff_eq_symm_apply]

/-- Reindexing the alphabet preserves KL exactly, including its totalized real sum. -/
theorem finiteKLReal_map_equiv {α β : Type*} [Fintype α] [Fintype β]
    (ν μ : FiniteLaw α) (e : α ≃ β) :
    finiteKLReal (finiteMap ν e) (finiteMap μ e) = finiteKLReal ν μ := by
  change finiteExpectation (finiteMap ν e)
    (fun b => Real.log ((finiteMap ν e).mass b/(finiteMap μ e).mass b)) = _
  rw [finiteExpectation_map]
  simp only [Function.comp_def, finiteMap_equiv_mass, Equiv.symm_apply_apply]
  rfl

/-- Reassociate (U,(V,(W,Z))) as ((U,W),(V,Z)). -/
def tensorReassociate (α β γ δ : Type*) : (α × (β × (γ × δ))) ≃ ((α × γ) × (β × δ)) where
  toFun z := ((z.1,z.2.2.1),(z.2.1,z.2.2.2))
  invFun z := (z.1.1,z.2.1,z.1.2,z.2.2)
  left_inv _ := rfl
  right_inv _ := rfl

/-- Sequential coupling: the second pair's changed joint law may depend on V. -/
def finiteTensorLift {α β γ δ : Type*} [Fintype α] [Fintype β] [Fintype γ] [Fintype δ]
    (μ : FiniteLaw (α × β)) (τ : β → FiniteLaw (γ × δ)) : FiniteLaw ((α × γ) × (β × δ)) :=
  finiteMap (finiteExtendRight μ τ) (tensorReassociate α β γ δ)

/-- The sequential coupling has the expected product of atom masses. -/
theorem finiteTensorLift_mass {α β γ δ : Type*} [Fintype α] [Fintype β] [Fintype γ] [Fintype δ]
    (μ : FiniteLaw (α × β)) (τ : β → FiniteLaw (γ × δ)) (z : (α × γ) × (β × δ)) :
    (finiteTensorLift μ τ).mass z = μ.mass (z.1.1,z.2.1) * (τ z.2.1).mass (z.1.2,z.2.2) := by
  rw [finiteTensorLift, finiteMap_equiv_mass]
  rfl

/-- Independent product of two bipartite reference laws, grouped by the two parties. -/
def finiteTensorProduct {α β γ δ : Type*} [Fintype α] [Fintype β] [Fintype γ] [Fintype δ]
    (μ : FiniteLaw (α × β)) (η : FiniteLaw (γ × δ)) : FiniteLaw ((α × γ) × (β × δ)) :=
  finiteTensorLift μ (fun _ => η)

/-- The first marginal of a sequential coupling is a product when the second
coupling's first marginal is fixed independently of V. -/
theorem finiteFirst_tensorLift {α β γ δ : Type*} [Fintype α] [Fintype β] [Fintype γ] [Fintype δ]
    (μ : FiniteLaw (α × β)) (τ : β → FiniteLaw (γ × δ)) (η : FiniteLaw γ)
    (hτ : ∀ b, finiteFirst (τ b) = η) :
    finiteFirst (finiteTensorLift μ τ) = finiteJoint (finiteFirst μ) (fun _ => η) := by
  ext z
  rw [finiteFirst_mass]
  simp only [Fintype.sum_prod_type, finiteTensorLift_mass]
  simp_rw [← Finset.mul_sum, ← finiteFirst_mass, hτ]
  simp only [finiteJoint, ← Finset.sum_mul, ← finiteFirst_mass]

/-- The second marginal follows the changed V marginal and the selected conditional Z laws. -/
theorem finiteSecond_tensorLift {α β γ δ : Type*} [Fintype α] [Fintype β] [Fintype γ] [Fintype δ]
    (μ : FiniteLaw (α × β)) (τ : β → FiniteLaw (γ × δ)) :
    finiteSecond (finiteTensorLift μ τ) = finiteJoint (finiteSecond μ) (fun b => finiteSecond (τ b)) := by
  ext z
  rw [finiteSecond_mass]
  simp only [Fintype.sum_prod_type, finiteTensorLift_mass]
  simp_rw [← Finset.mul_sum, ← finiteSecond_mass]
  simp only [finiteJoint, ← Finset.sum_mul, ← finiteSecond_mass]

/-- KL chain rule for the sequential product coupling. -/
theorem finiteKLReal_tensorLift {α β γ δ : Type*} [Fintype α] [Fintype β] [Fintype γ] [Fintype δ]
    (ν μ : FiniteLaw (α × β)) (τ : β → FiniteLaw (γ × δ)) (η : FiniteLaw (γ × δ))
    (hμ : ∀ z, 0 < μ.mass z) (hη : ∀ z, 0 < η.mass z) :
    finiteKLReal (finiteTensorLift ν τ) (finiteTensorProduct μ η) = finiteKLReal ν μ +
      ∑ b, (finiteSecond ν).mass b * finiteKLReal (τ b) η := by
  rw [finiteTensorLift, finiteTensorProduct, finiteTensorLift, finiteKLReal_map_equiv]
  exact finiteKLReal_extendRight ν μ τ (fun _ => η) hμ (fun _ z => hη z)

/-- Entropy lifting tensorizes with the same coefficient for independent reference pairs.
The changed V,Z law need not be a product: its conditional Z laws determine the
second sequential coupling, and the KL chain rule pays exactly their average cost. -/
theorem entropyLifting_tensor {α β γ δ : Type*} [Fintype α] [Fintype β] [Fintype γ] [Fintype δ]
    (μ : FiniteLaw (α × β)) (η : FiniteLaw (γ × δ))
    (hμ : ∀ z, 0 < μ.mass z) (hη : ∀ z, 0 < η.mass z) {a : ℝ}
    (hμlift : EntropyLifting μ a) (hηlift : EntropyLifting η a) :
    EntropyLifting (finiteTensorProduct μ η) a := by
  classical
  intro ν
  obtain ⟨κ,hκ,hκcost⟩ := hμlift (finiteFirst ν)
  choose τ hτ hτcost using fun b => hηlift (finiteConditionalLaw ν b)
  refine ⟨finiteTensorLift κ τ, ⟨?_, ?_⟩, ?_⟩
  · rw [finiteFirst_tensorLift κ τ (finiteFirst η) (fun b => (hτ b).1)]
    change _ = finiteFirst (finiteTensorLift μ (fun _ => η))
    rw [finiteFirst_tensorLift μ (fun _ => η) (finiteFirst η) (fun _ => rfl), hκ.1]
  · rw [finiteSecond_tensorLift, hκ.2]
    have he : (fun b => finiteSecond (τ b)) = finiteConditionalLaw ν := funext (fun b => (hτ b).2)
    rw [he, finiteJoint_conditional]
  · rw [finiteKLReal_tensorLift κ μ τ η hμ hη, hκ.2]
    change _ ≤ finiteKLReal ν (finiteSecond (finiteTensorLift μ (fun _ => η)))
    rw [finiteSecond_tensorLift]
    have hchain := finiteKLReal_joint (finiteFirst ν) (finiteSecond μ) (finiteConditionalLaw ν)
      (fun _ => finiteSecond η) (finiteSecond_pos μ hμ) (fun _ => finiteSecond_pos η hη)
    rw [finiteJoint_conditional] at hchain
    rw [hchain]
    have hsum := Finset.sum_le_sum (s := Finset.univ)
      (fun b _ => mul_le_mul_of_nonneg_left (hτcost b) ((finiteFirst ν).nonneg b))
    have he : (∑ b, (finiteFirst ν).mass b * (a * finiteKLReal (τ b) η)) =
        a * ∑ b, (finiteFirst ν).mass b * finiteKLReal (τ b) η := by
      rw [Finset.mul_sum]
      apply Finset.sum_congr rfl
      intro b _
      ring
    rw [he] at hsum
    nlinarith

/-- A probability law on a singleton alphabet is unique. -/
theorem finiteLaw_eq_of_subsingleton {α : Type*} [Fintype α] [Subsingleton α]
    (μ ν : FiniteLaw α) : μ = ν := by
  ext a
  letI : Unique α := ⟨⟨a⟩, fun b => Subsingleton.elim b a⟩
  have hμ : μ.mass a = 1 := by simpa only [Fintype.sum_unique, Subsingleton.elim (default : α) a] using μ.total
  have hν : ν.mass a = 1 := by simpa only [Fintype.sum_unique, Subsingleton.elim (default : α) a] using ν.total
  rw [hμ,hν]

/-- A constant right variable has the trivial entropy-lifting property. -/
theorem entropyLifting_subsingleton_right {α β : Type*} [Fintype α] [Fintype β] [Subsingleton β]
    (μ : FiniteLaw (α × β)) (a : ℝ) : EntropyLifting μ a := by
  intro ν
  have hν := finiteLaw_eq_of_subsingleton ν (finiteSecond μ)
  subst ν
  exact ⟨μ, ⟨rfl,rfl⟩, by simp [finiteKLReal_self]⟩

/-- Add a leading Boolean coordinate to a smaller cube. -/
def cubeConsEquiv (n : ℕ) : (BooleanCube n × Bool) ≃ BooleanCube (n+1) where
  toFun z := Fin.cons z.2 z.1
  invFun x := (Fin.tail x,x 0)
  left_inv z := by cases z; rfl
  right_inv x := by funext i; exact Fin.cases rfl (fun _ => rfl) i

/-- Positive atom probabilities for a nondegenerate noisy cube. -/
theorem cubeNoiseLaw_pos (n : ℕ) {ρ : ℝ} (hρ : ρ ∈ Set.Ioo (-1 : ℝ) 1)
    (z : BooleanCube n × BooleanCube n) :
    0 < (cubeNoiseLaw n ρ ⟨hρ.1.le,hρ.2.le⟩).mass z := by
  apply mul_pos (inv_pos.mpr (Nat.cast_pos.mpr Fintype.card_pos))
  apply Finset.prod_pos
  intro i _
  split_ifs <;> linarith [hρ.1,hρ.2]

/-- An (n+1)-bit noisy cube is exactly the independent product of the n-bit cube
and one binary symmetric pair, with the coordinates reassembled. -/
theorem cubeNoiseLaw_succ (n : ℕ) (ρ : ℝ) (hρ : ρ ∈ Set.Icc (-1 : ℝ) 1) :
    finiteMap (finiteTensorProduct (cubeNoiseLaw n ρ hρ) (binarySymmetricLaw ρ hρ))
      ((cubeConsEquiv n).prodCongr (cubeConsEquiv n)) = cubeNoiseLaw (n+1) ρ hρ := by
  ext z
  rw [finiteMap_equiv_mass, finiteTensorProduct, finiteTensorLift_mass]
  simp only [Equiv.prodCongr_symm, Equiv.prodCongr_apply, cubeConsEquiv, cubeNoiseLaw,
    binarySymmetricLaw]
  simp only [BooleanCube, Fintype.card_fun, Fintype.card_bool, Fintype.card_fin,
    Nat.cast_pow, Nat.cast_ofNat]
  change (2^n : ℝ)⁻¹ * cubeNoiseKernel ρ (Fin.tail z.1) (Fin.tail z.2) *
    (if z.1 0 = z.2 0 then (1+ρ)/4 else (1-ρ)/4) =
    (2^(n+1) : ℝ)⁻¹ * cubeNoiseKernel ρ z.1 z.2
  unfold cubeNoiseKernel
  rw [Fin.prod_univ_succ]
  simp only [Fin.tail]
  rw [pow_succ]
  split_ifs <;> field_simp <;> ring

/-- Entropy lifting tensorizes across every bit of the uniformly distributed noisy cube. -/
theorem entropyLifting_cubeNoise (n : ℕ) {ρ : ℝ} (hρ : ρ ∈ Set.Ioo (-1 : ℝ) 1) :
    EntropyLifting (cubeNoiseLaw n ρ ⟨hρ.1.le,hρ.2.le⟩) (1-ρ^2) := by
  have ha : 0 ≤ 1-ρ^2 := by nlinarith [hρ.1,hρ.2]
  induction n with
  | zero => exact entropyLifting_subsingleton_right _ _
  | succ n ih =>
    let μ := finiteTensorProduct (cubeNoiseLaw n ρ ⟨hρ.1.le,hρ.2.le⟩)
      (binarySymmetricLaw ρ ⟨hρ.1.le,hρ.2.le⟩)
    have hμ : ∀ z, 0 < μ.mass z := by
      intro z
      rw [show μ = finiteTensorLift (cubeNoiseLaw n ρ ⟨hρ.1.le,hρ.2.le⟩)
        (fun _ => binarySymmetricLaw ρ ⟨hρ.1.le,hρ.2.le⟩) from rfl, finiteTensorLift_mass]
      exact mul_pos (cubeNoiseLaw_pos n hρ _) (binarySymmetricLaw_pos hρ _)
    have hlift : EntropyLifting μ (1-ρ^2) :=
      entropyLifting_tensor _ _ (cubeNoiseLaw_pos n hρ) (binarySymmetricLaw_pos hρ)
        ih (entropyLifting_binarySymmetric hρ)
    have hmap := entropyLifting_map μ hμ (cubeConsEquiv n) (cubeConsEquiv n)
      (finiteMap_pos _ (finiteSecond_pos μ hμ) _ (cubeConsEquiv n).surjective) ha hlift
    change EntropyLifting (finiteMap μ ((cubeConsEquiv n).prodCongr (cubeConsEquiv n))) (1-ρ^2) at hmap
    dsimp only [μ] at hmap
    exact (congrArg (fun μ => EntropyLifting μ (1-ρ^2))
      (cubeNoiseLaw_succ n ρ ⟨hρ.1.le,hρ.2.le⟩)).mp hmap

/-- The noisy cube's reverse coefficient is at most rho². -/
theorem sDagger_cubeNoise_le (n : ℕ) {ρ : ℝ} (hρ : ρ ∈ Set.Ioo (-1 : ℝ) 1) :
    sDagger (cubeNoiseLaw n ρ ⟨hρ.1.le,hρ.2.le⟩) ≤ ρ^2 := by
  have ha : 1-ρ^2 ∈ Set.Icc (0 : ℝ) 1 := ⟨by nlinarith [hρ.1,hρ.2],by nlinarith [sq_nonneg ρ]⟩
  have h := reverseComplement_ge_of_lifting _ (cubeNoiseLaw_pos n hρ) ha (entropyLifting_cubeNoise n hρ)
  have hreal := ENNReal.toReal_mono
    (ne_top_of_le_ne_top (by simp) (reverseComplement_le_one _)) h
  rw [ENNReal.toReal_ofReal ha.1] at hreal
  unfold sDagger
  linarith

/-- Strict increase of the tilted marginal probability. -/
theorem bscTiltMean_strictMono (k : ℝ) : StrictMono (bscTiltMean k) :=
  strictMono_of_hasDerivAt_pos (hasDerivAt_bscTiltMean k) (bscTiltVariance_pos k)

/-- A nonzero tilt changes the marginal and is therefore admissible in the defining infimum. -/
theorem bscTilt_admissible (k t : ℝ) (ht : t ≠ 0) :
    reverseAdmissible (bscTilt k 0) (finiteSecond (bscTilt k t)) := by
  apply reverseAdmissible_of_ne _ _ (bscTilt_pos k 0)
  intro he
  have h := congrArg (fun ν : FiniteLaw Bool => ν.mass true) he
  rw [bscTilt_second_true,bscTilt_second_true] at h
  exact ht ((bscTiltMean_strictMono k).injective h)

/-- The common tilt's cost equals the actual minimum in the reverse coefficient. -/
theorem bscTilt_transportCost (k t : ℝ) :
    finiteTransportCost (bscTilt k 0) (finiteSecond (bscTilt k t)) =
      ENNReal.ofReal (bscTiltCost k t) := by
  have hf : finiteTransportFeasible (bscTilt k 0) (bscTilt k t) (finiteSecond (bscTilt k t)) :=
    ⟨by rw [bscTilt_first,bscTilt_first],rfl⟩
  have hval : finiteKL (bscTilt k t) (bscTilt k 0) = ENNReal.ofReal (bscTiltCost k t) := by
    rw [finiteKL_of_supported _ _ (fun z hz => ((bscTilt_pos k 0 z).ne' hz).elim), bscTiltCost_eq_KL]
  apply le_antisymm ((finiteTransportCost_le _ _ _ hf).trans_eq hval)
  apply le_sInf
  rintro v ⟨κ,hκ,rfl⟩
  rw [finiteKL_of_supported _ _ (fun z hz => ((bscTilt_pos k 0 z).ne' hz).elim), bscTiltCost_eq_KL]
  exact ENNReal.ofReal_le_ofReal (bscTilt_minimizes k t κ hκ)

/-- The reverse complement is bounded by every nontrivial tilt's entropy ratio. -/
theorem bsc_complement_le_ratio (k t : ℝ) (ht : t ≠ 0) :
    (reverseComplement (bscTilt k 0)).toReal ≤
      finiteBinaryKL (bscTiltMean k t) (1/2) / bscTiltCost k t := by
  have hadm := bscTilt_admissible k t ht
  have hn : finiteKLReal (finiteSecond (bscTilt k t)) (finiteSecond (bscTilt k 0)) =
      finiteBinaryKL (bscTiltMean k t) (1/2) := by
    rw [bscTilt_second_zero]
    nth_rw 1 [finiteLaw_bool_eq_bernoulli (finiteSecond (bscTilt k t))]
    change finiteKLReal (bernoulliLaw _ _) (bernoulliLaw _ _) = _
    convert! finiteKLReal_bernoulli _ _ using 1 <;> simp [bscTilt_second_true]
  have h := reverseComplement_le_ratio _ _ hadm
  have hreal := ENNReal.toReal_mono
    (ENNReal.div_ne_top (by rw [finiteKL_of_supported _ _ hadm.2]; exact ENNReal.ofReal_ne_top)
      (finiteTransportCost_pos _ _ hadm).ne') h
  rw [ENNReal.toReal_div, finiteKL_toReal _ _ hadm.2, hn,
    bscTilt_transportCost, ENNReal.toReal_ofReal] at hreal
  · exact hreal
  · rw [bscTiltCost_eq_KL]
    exact finiteKLReal_nonneg _ _ (fun z hz => ((bscTilt_pos k 0 z).ne' hz).elim)

/-- Conditional variance at the symmetric reference. -/
theorem bscTiltVariance_zero (k : ℝ) : bscTiltVariance k 0 = bscFactor k / 4 := by
  simp [bscTiltVariance, bscFactor, bscCorrelation, Real.sigmoid_neg]
  ring

/-- The derivative of marginal log odds at the symmetric reference is 1-rho². -/
theorem bsc_logOdds_deriv_zero (k : ℝ) :
    HasDerivAt (fun t => logOdds (bscTiltMean k t)) (bscFactor k) 0 := by
  have h := (hasDerivAt_logOdds (bscTiltMean_mem k 0)).comp 0 (hasDerivAt_bscTiltMean k 0)
  convert! h using 1
  rw [bscTiltMean_zero,bscTiltVariance_zero]
  ring

/-- The marginal-to-conditional entropy ratio tends to 1-rho² for small nonzero tilts. -/
theorem bsc_entropy_ratio_limit (k : ℝ) :
    Filter.Tendsto (fun t => finiteBinaryKL (bscTiltMean k t) (1/2) / bscTiltCost k t)
      (nhdsWithin 0 {0}ᶜ) (nhds (bscFactor k)) := by
  have hzero : logOdds (bscTiltMean k 0) = 0 := by rw [bscTiltMean_zero]; norm_num [logOdds]
  have hlog : Filter.Tendsto (fun t => logOdds (bscTiltMean k t)/t)
      (nhdsWithin 0 {0}ᶜ) (nhds (bscFactor k)) := by
    convert! (bsc_logOdds_deriv_zero k).tendsto_slope using 1
    ext t
    simp [slope_def_field, hzero]
  have hnum (t : ℝ) : HasDerivAt (fun t => finiteBinaryKL (bscTiltMean k t) (1/2))
      (logOdds (bscTiltMean k t) * bscTiltVariance k t) t := by
    have h := (hasDerivAt_finiteBinaryKL (q := (1/2 : ℝ)) (bscTiltMean_mem k t)
      (by constructor <;> norm_num)).comp t (hasDerivAt_bscTiltMean k t)
    convert! h using 1
    norm_num [logOdds]
  apply HasDerivAt.lhopital_zero_nhdsNE
    (Filter.Eventually.of_forall hnum)
    (Filter.Eventually.of_forall (hasDerivAt_bscTiltCost k))
  · filter_upwards [self_mem_nhdsWithin] with t ht
    exact mul_ne_zero (by simpa using ht) (bscTiltVariance_pos k t).ne'
  · simpa only [bscTiltMean_zero,finiteBinaryKL_self] using
      ((hnum 0).continuousAt.tendsto.mono_left nhdsWithin_le_nhds)
  · simpa [bscTiltCost,finiteBinaryKL_self] using
      ((hasDerivAt_bscTiltCost k 0).continuousAt.tendsto.mono_left nhdsWithin_le_nhds)
  · simpa only [mul_div_mul_right _ _ (bscTiltVariance_pos k _).ne'] using hlog

/-- Sharp reverse complement of a nondegenerate binary symmetric reference. -/
theorem bsc_reverseComplement_exact (k : ℝ) :
    (reverseComplement (bscTilt k 0)).toReal = bscFactor k := by
  have hupper : (reverseComplement (bscTilt k 0)).toReal ≤ bscFactor k :=
    le_of_tendsto_of_tendsto tendsto_const_nhds (bsc_entropy_ratio_limit k)
      (by filter_upwards [self_mem_nhdsWithin] with t ht; exact bsc_complement_le_ratio k t (by simpa using ht))
  have h := reverseComplement_ge_of_lifting _ (bscTilt_pos k 0)
    ⟨(bscFactor_mem k).1.le,(bscFactor_mem k).2⟩ (entropyLifting_bscTilt k)
  have hlower := ENNReal.toReal_mono
    (ne_top_of_le_ne_top (by simp) (reverseComplement_le_one _)) h
  rw [ENNReal.toReal_ofReal (bscFactor_mem k).1.le] at hlower
  exact le_antisymm hupper hlower

/-- Exact reverse-hypercontractivity coefficient of the binary symmetric channel. -/
theorem sDagger_binarySymmetric {ρ : ℝ} (hρ : ρ ∈ Set.Ioo (-1 : ℝ) 1) :
    sDagger (binarySymmetricLaw ρ ⟨hρ.1.le,hρ.2.le⟩) = ρ^2 := by
  rw [← bscTilt_eq_binarySymmetric hρ, sDagger, bsc_reverseComplement_exact,
    bscFactor, bscCorrelation_logOdds hρ]
  ring

/-- Projecting an independent pair of joint laws onto its second pair recovers that law. -/
theorem finiteTensorProduct_project_right {α β γ δ : Type*}
    [Fintype α] [Fintype β] [Fintype γ] [Fintype δ]
    (μ : FiniteLaw (α × β)) (η : FiniteLaw (γ × δ)) :
    finiteMap (finiteTensorProduct μ η) (fun z => (z.1.2,z.2.2)) = η := by
  unfold finiteTensorProduct finiteTensorLift
  rw [finiteMap_comp]
  have h := congrArg finiteSecond (finiteSecond_extendRight μ (fun _ => η))
  rw [finiteSecond_joint_const] at h
  unfold finiteSecond at h
  rw [finiteMap_comp] at h
  exact h

/-- A coordinate pair of the noisy cube has exactly the binary symmetric law. -/
theorem cubeNoiseLaw_head (n : ℕ) (ρ : ℝ) (hρ : ρ ∈ Set.Icc (-1 : ℝ) 1) :
    finiteMap (cubeNoiseLaw (n+1) ρ hρ) (fun z => (z.1 0,z.2 0)) =
      binarySymmetricLaw ρ hρ := by
  rw [← cubeNoiseLaw_succ n ρ hρ, finiteMap_comp]
  exact finiteTensorProduct_project_right _ _

/-- Exact reverse coefficient of every positive-dimensional nondegenerate noisy cube. -/
theorem sDagger_cubeNoise {n : ℕ} (hn : 1 ≤ n) {ρ : ℝ}
    (hρ : ρ ∈ Set.Ioo (-1 : ℝ) 1) :
    sDagger (cubeNoiseLaw n ρ ⟨hρ.1.le,hρ.2.le⟩) = ρ^2 := by
  apply le_antisymm (sDagger_cubeNoise_le n hρ)
  cases n with
  | zero => omega
  | succ n =>
    have hout : ∀ z, 0 < (finiteMap (cubeNoiseLaw (n+1) ρ ⟨hρ.1.le,hρ.2.le⟩)
        (fun z => (z.1 0,z.2 0))).mass z := by
      have he := cubeNoiseLaw_head n ρ ⟨hρ.1.le,hρ.2.le⟩
      convert! (congrArg (fun μ : FiniteLaw (Bool × Bool) => ∀ z, 0 < μ.mass z) he).mpr
        (binarySymmetricLaw_pos hρ) using 1
    have h := sDagger_map_le _ (cubeNoiseLaw_pos (n+1) hρ)
      (fun x => x 0) (fun y => y 0) hout
    have he := congrArg sDagger (cubeNoiseLaw_head n ρ ⟨hρ.1.le,hρ.2.le⟩)
    have he' := he.trans (sDagger_binarySymmetric hρ)
    convert! h using 1
    exact he'.symm

end

end Auto
